// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: xenon/v1/execution.proto

package xenonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecutionCommand_Kind int32

const (
	ExecutionCommand_UNSPECIFIED      ExecutionCommand_Kind = 0
	ExecutionCommand_CREATE           ExecutionCommand_Kind = 1
	ExecutionCommand_UPDATE           ExecutionCommand_Kind = 2
	ExecutionCommand_CONFLICT_RESOLVE ExecutionCommand_Kind = 3
	ExecutionCommand_SET              ExecutionCommand_Kind = 4
	ExecutionCommand_GET              ExecutionCommand_Kind = 5
	ExecutionCommand_GET_CURRENT      ExecutionCommand_Kind = 6
	ExecutionCommand_DELETE           ExecutionCommand_Kind = 7
	ExecutionCommand_DELETE_CURRENT   ExecutionCommand_Kind = 8
	ExecutionCommand_LIST             ExecutionCommand_Kind = 9
)

// Enum value maps for ExecutionCommand_Kind.
var (
	ExecutionCommand_Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "CREATE",
		2: "UPDATE",
		3: "CONFLICT_RESOLVE",
		4: "SET",
		5: "GET",
		6: "GET_CURRENT",
		7: "DELETE",
		8: "DELETE_CURRENT",
		9: "LIST",
	}
	ExecutionCommand_Kind_value = map[string]int32{
		"UNSPECIFIED":      0,
		"CREATE":           1,
		"UPDATE":           2,
		"CONFLICT_RESOLVE": 3,
		"SET":              4,
		"GET":              5,
		"GET_CURRENT":      6,
		"DELETE":           7,
		"DELETE_CURRENT":   8,
		"LIST":             9,
	}
)

func (x ExecutionCommand_Kind) Enum() *ExecutionCommand_Kind {
	p := new(ExecutionCommand_Kind)
	*p = x
	return p
}

func (x ExecutionCommand_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionCommand_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_execution_proto_enumTypes[0].Descriptor()
}

func (ExecutionCommand_Kind) Type() protoreflect.EnumType {
	return &file_xenon_v1_execution_proto_enumTypes[0]
}

func (x ExecutionCommand_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionCommand_Kind.Descriptor instead.
func (ExecutionCommand_Kind) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{5, 0}
}

type ExecutionResult_Error int32

const (
	ExecutionResult_NONE                      ExecutionResult_Error = 0
	ExecutionResult_NOT_FOUND                 ExecutionResult_Error = 1
	ExecutionResult_UNAVAILABLE               ExecutionResult_Error = 2
	ExecutionResult_INTERNAL                  ExecutionResult_Error = 3
	ExecutionResult_CONDITION_FAILED          ExecutionResult_Error = 4
	ExecutionResult_WORKFLOW_CONDITION_FAILED ExecutionResult_Error = 5
	ExecutionResult_CURRENT_CONDITION_FAILED  ExecutionResult_Error = 6
	ExecutionResult_OWNERSHIP_LOST            ExecutionResult_Error = 7
)

// Enum value maps for ExecutionResult_Error.
var (
	ExecutionResult_Error_name = map[int32]string{
		0: "NONE",
		1: "NOT_FOUND",
		2: "UNAVAILABLE",
		3: "INTERNAL",
		4: "CONDITION_FAILED",
		5: "WORKFLOW_CONDITION_FAILED",
		6: "CURRENT_CONDITION_FAILED",
		7: "OWNERSHIP_LOST",
	}
	ExecutionResult_Error_value = map[string]int32{
		"NONE":                      0,
		"NOT_FOUND":                 1,
		"UNAVAILABLE":               2,
		"INTERNAL":                  3,
		"CONDITION_FAILED":          4,
		"WORKFLOW_CONDITION_FAILED": 5,
		"CURRENT_CONDITION_FAILED":  6,
		"OWNERSHIP_LOST":            7,
	}
)

func (x ExecutionResult_Error) Enum() *ExecutionResult_Error {
	p := new(ExecutionResult_Error)
	*p = x
	return p
}

func (x ExecutionResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecutionResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_execution_proto_enumTypes[1].Descriptor()
}

func (ExecutionResult_Error) Type() protoreflect.EnumType {
	return &file_xenon_v1_execution_proto_enumTypes[1]
}

func (x ExecutionResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecutionResult_Error.Descriptor instead.
func (ExecutionResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{7, 0}
}

type ExecutionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Partition       string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandSha256   []byte                 `protobuf:"bytes,4,opt,name=command_sha256,json=commandSha256,proto3" json:"command_sha256,omitempty"`
	Command         *ExecutionCommand      `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_xenon_v1_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecutionRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *ExecutionRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *ExecutionRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecutionRequest) GetCommandSha256() []byte {
	if x != nil {
		return x.CommandSha256
	}
	return nil
}

func (x *ExecutionRequest) GetCommand() *ExecutionCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type ExecutionChasmNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *HistoryBlob           `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Data          *HistoryBlob           `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	CassandraBlob *HistoryBlob           `protobuf:"bytes,3,opt,name=cassandra_blob,json=cassandraBlob,proto3" json:"cassandra_blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionChasmNode) Reset() {
	*x = ExecutionChasmNode{}
	mi := &file_xenon_v1_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionChasmNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionChasmNode) ProtoMessage() {}

func (x *ExecutionChasmNode) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionChasmNode.ProtoReflect.Descriptor instead.
func (*ExecutionChasmNode) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutionChasmNode) GetMetadata() *HistoryBlob {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ExecutionChasmNode) GetData() *HistoryBlob {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ExecutionChasmNode) GetCassandraBlob() *HistoryBlob {
	if x != nil {
		return x.CassandraBlob
	}
	return nil
}

type ExecutionTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int32                  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	CategoryType  int32                  `protobuf:"varint,2,opt,name=category_type,json=categoryType,proto3" json:"category_type,omitempty"`
	TaskId        int64                  `protobuf:"varint,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FireSeconds   int64                  `protobuf:"varint,4,opt,name=fire_seconds,json=fireSeconds,proto3" json:"fire_seconds,omitempty"`
	FireNanos     int32                  `protobuf:"varint,5,opt,name=fire_nanos,json=fireNanos,proto3" json:"fire_nanos,omitempty"`
	Blob          *HistoryBlob           `protobuf:"bytes,6,opt,name=blob,proto3" json:"blob,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionTask) Reset() {
	*x = ExecutionTask{}
	mi := &file_xenon_v1_execution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionTask) ProtoMessage() {}

func (x *ExecutionTask) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionTask.ProtoReflect.Descriptor instead.
func (*ExecutionTask) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionTask) GetCategoryId() int32 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ExecutionTask) GetCategoryType() int32 {
	if x != nil {
		return x.CategoryType
	}
	return 0
}

func (x *ExecutionTask) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *ExecutionTask) GetFireSeconds() int64 {
	if x != nil {
		return x.FireSeconds
	}
	return 0
}

func (x *ExecutionTask) GetFireNanos() int32 {
	if x != nil {
		return x.FireNanos
	}
	return 0
}

func (x *ExecutionTask) GetBlob() *HistoryBlob {
	if x != nil {
		return x.Blob
	}
	return nil
}

type ExecutionImage struct {
	state               protoimpl.MessageState         `protogen:"open.v1"`
	NamespaceId         string                         `protobuf:"bytes,1,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WorkflowId          string                         `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId               string                         `protobuf:"bytes,3,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ExecutionInfoProto  []byte                         `protobuf:"bytes,4,opt,name=execution_info_proto,json=executionInfoProto,proto3" json:"execution_info_proto,omitempty"`
	ExecutionStateProto []byte                         `protobuf:"bytes,5,opt,name=execution_state_proto,json=executionStateProto,proto3" json:"execution_state_proto,omitempty"`
	ExecutionInfoBlob   *HistoryBlob                   `protobuf:"bytes,6,opt,name=execution_info_blob,json=executionInfoBlob,proto3" json:"execution_info_blob,omitempty"`
	ExecutionStateBlob  *HistoryBlob                   `protobuf:"bytes,7,opt,name=execution_state_blob,json=executionStateBlob,proto3" json:"execution_state_blob,omitempty"`
	NextEventId         int64                          `protobuf:"varint,8,opt,name=next_event_id,json=nextEventId,proto3" json:"next_event_id,omitempty"`
	StartVersion        int64                          `protobuf:"varint,9,opt,name=start_version,json=startVersion,proto3" json:"start_version,omitempty"`
	LastWriteVersion    int64                          `protobuf:"varint,10,opt,name=last_write_version,json=lastWriteVersion,proto3" json:"last_write_version,omitempty"`
	DbRecordVersion     int64                          `protobuf:"varint,11,opt,name=db_record_version,json=dbRecordVersion,proto3" json:"db_record_version,omitempty"`
	Condition           int64                          `protobuf:"varint,12,opt,name=condition,proto3" json:"condition,omitempty"`
	Activities          map[int64]*HistoryBlob         `protobuf:"bytes,13,rep,name=activities,proto3" json:"activities,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Timers              map[string]*HistoryBlob        `protobuf:"bytes,14,rep,name=timers,proto3" json:"timers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Children            map[int64]*HistoryBlob         `protobuf:"bytes,15,rep,name=children,proto3" json:"children,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cancels             map[int64]*HistoryBlob         `protobuf:"bytes,16,rep,name=cancels,proto3" json:"cancels,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Signals             map[int64]*HistoryBlob         `protobuf:"bytes,17,rep,name=signals,proto3" json:"signals,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Chasm               map[string]*ExecutionChasmNode `protobuf:"bytes,18,rep,name=chasm,proto3" json:"chasm,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SignalRequestedIds  []string                       `protobuf:"bytes,19,rep,name=signal_requested_ids,json=signalRequestedIds,proto3" json:"signal_requested_ids,omitempty"`
	BufferedEvents      []*HistoryBlob                 `protobuf:"bytes,20,rep,name=buffered_events,json=bufferedEvents,proto3" json:"buffered_events,omitempty"`
	Checksum            *HistoryBlob                   `protobuf:"bytes,21,opt,name=checksum,proto3" json:"checksum,omitempty"`
	Tasks               []*ExecutionTask               `protobuf:"bytes,22,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExecutionImage) Reset() {
	*x = ExecutionImage{}
	mi := &file_xenon_v1_execution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionImage) ProtoMessage() {}

func (x *ExecutionImage) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionImage.ProtoReflect.Descriptor instead.
func (*ExecutionImage) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutionImage) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ExecutionImage) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionImage) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionImage) GetExecutionInfoProto() []byte {
	if x != nil {
		return x.ExecutionInfoProto
	}
	return nil
}

func (x *ExecutionImage) GetExecutionStateProto() []byte {
	if x != nil {
		return x.ExecutionStateProto
	}
	return nil
}

func (x *ExecutionImage) GetExecutionInfoBlob() *HistoryBlob {
	if x != nil {
		return x.ExecutionInfoBlob
	}
	return nil
}

func (x *ExecutionImage) GetExecutionStateBlob() *HistoryBlob {
	if x != nil {
		return x.ExecutionStateBlob
	}
	return nil
}

func (x *ExecutionImage) GetNextEventId() int64 {
	if x != nil {
		return x.NextEventId
	}
	return 0
}

func (x *ExecutionImage) GetStartVersion() int64 {
	if x != nil {
		return x.StartVersion
	}
	return 0
}

func (x *ExecutionImage) GetLastWriteVersion() int64 {
	if x != nil {
		return x.LastWriteVersion
	}
	return 0
}

func (x *ExecutionImage) GetDbRecordVersion() int64 {
	if x != nil {
		return x.DbRecordVersion
	}
	return 0
}

func (x *ExecutionImage) GetCondition() int64 {
	if x != nil {
		return x.Condition
	}
	return 0
}

func (x *ExecutionImage) GetActivities() map[int64]*HistoryBlob {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *ExecutionImage) GetTimers() map[string]*HistoryBlob {
	if x != nil {
		return x.Timers
	}
	return nil
}

func (x *ExecutionImage) GetChildren() map[int64]*HistoryBlob {
	if x != nil {
		return x.Children
	}
	return nil
}

func (x *ExecutionImage) GetCancels() map[int64]*HistoryBlob {
	if x != nil {
		return x.Cancels
	}
	return nil
}

func (x *ExecutionImage) GetSignals() map[int64]*HistoryBlob {
	if x != nil {
		return x.Signals
	}
	return nil
}

func (x *ExecutionImage) GetChasm() map[string]*ExecutionChasmNode {
	if x != nil {
		return x.Chasm
	}
	return nil
}

func (x *ExecutionImage) GetSignalRequestedIds() []string {
	if x != nil {
		return x.SignalRequestedIds
	}
	return nil
}

func (x *ExecutionImage) GetBufferedEvents() []*HistoryBlob {
	if x != nil {
		return x.BufferedEvents
	}
	return nil
}

func (x *ExecutionImage) GetChecksum() *HistoryBlob {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *ExecutionImage) GetTasks() []*ExecutionTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ExecutionMutation struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Upsert                   *ExecutionImage        `protobuf:"bytes,1,opt,name=upsert,proto3" json:"upsert,omitempty"`
	DeleteActivities         []int64                `protobuf:"varint,2,rep,packed,name=delete_activities,json=deleteActivities,proto3" json:"delete_activities,omitempty"`
	DeleteTimers             []string               `protobuf:"bytes,3,rep,name=delete_timers,json=deleteTimers,proto3" json:"delete_timers,omitempty"`
	DeleteChildren           []int64                `protobuf:"varint,4,rep,packed,name=delete_children,json=deleteChildren,proto3" json:"delete_children,omitempty"`
	DeleteCancels            []int64                `protobuf:"varint,5,rep,packed,name=delete_cancels,json=deleteCancels,proto3" json:"delete_cancels,omitempty"`
	DeleteSignals            []int64                `protobuf:"varint,6,rep,packed,name=delete_signals,json=deleteSignals,proto3" json:"delete_signals,omitempty"`
	DeleteChasm              []string               `protobuf:"bytes,7,rep,name=delete_chasm,json=deleteChasm,proto3" json:"delete_chasm,omitempty"`
	DeleteSignalRequestedIds []string               `protobuf:"bytes,8,rep,name=delete_signal_requested_ids,json=deleteSignalRequestedIds,proto3" json:"delete_signal_requested_ids,omitempty"`
	ClearBufferedEvents      bool                   `protobuf:"varint,9,opt,name=clear_buffered_events,json=clearBufferedEvents,proto3" json:"clear_buffered_events,omitempty"`
	NewBufferedEvents        *HistoryBlob           `protobuf:"bytes,10,opt,name=new_buffered_events,json=newBufferedEvents,proto3" json:"new_buffered_events,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExecutionMutation) Reset() {
	*x = ExecutionMutation{}
	mi := &file_xenon_v1_execution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionMutation) ProtoMessage() {}

func (x *ExecutionMutation) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionMutation.ProtoReflect.Descriptor instead.
func (*ExecutionMutation) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{4}
}

func (x *ExecutionMutation) GetUpsert() *ExecutionImage {
	if x != nil {
		return x.Upsert
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteActivities() []int64 {
	if x != nil {
		return x.DeleteActivities
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteTimers() []string {
	if x != nil {
		return x.DeleteTimers
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteChildren() []int64 {
	if x != nil {
		return x.DeleteChildren
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteCancels() []int64 {
	if x != nil {
		return x.DeleteCancels
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteSignals() []int64 {
	if x != nil {
		return x.DeleteSignals
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteChasm() []string {
	if x != nil {
		return x.DeleteChasm
	}
	return nil
}

func (x *ExecutionMutation) GetDeleteSignalRequestedIds() []string {
	if x != nil {
		return x.DeleteSignalRequestedIds
	}
	return nil
}

func (x *ExecutionMutation) GetClearBufferedEvents() bool {
	if x != nil {
		return x.ClearBufferedEvents
	}
	return false
}

func (x *ExecutionMutation) GetNewBufferedEvents() *HistoryBlob {
	if x != nil {
		return x.NewBufferedEvents
	}
	return nil
}

type ExecutionCommand struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Kind                     ExecutionCommand_Kind  `protobuf:"varint,1,opt,name=kind,proto3,enum=xenon.v1.ExecutionCommand_Kind" json:"kind,omitempty"`
	ShardId                  int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	RangeId                  int64                  `protobuf:"varint,3,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	Mode                     int32                  `protobuf:"varint,4,opt,name=mode,proto3" json:"mode,omitempty"`
	ArchetypeId              uint32                 `protobuf:"varint,5,opt,name=archetype_id,json=archetypeId,proto3" json:"archetype_id,omitempty"`
	PreviousRunId            string                 `protobuf:"bytes,6,opt,name=previous_run_id,json=previousRunId,proto3" json:"previous_run_id,omitempty"`
	PreviousLastWriteVersion int64                  `protobuf:"varint,7,opt,name=previous_last_write_version,json=previousLastWriteVersion,proto3" json:"previous_last_write_version,omitempty"`
	Snapshot                 *ExecutionImage        `protobuf:"bytes,8,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Mutation                 *ExecutionMutation     `protobuf:"bytes,9,opt,name=mutation,proto3" json:"mutation,omitempty"`
	NewSnapshot              *ExecutionImage        `protobuf:"bytes,10,opt,name=new_snapshot,json=newSnapshot,proto3" json:"new_snapshot,omitempty"`
	CurrentMutation          *ExecutionMutation     `protobuf:"bytes,11,opt,name=current_mutation,json=currentMutation,proto3" json:"current_mutation,omitempty"`
	HistoryPrewrites         []*HistoryCommand      `protobuf:"bytes,12,rep,name=history_prewrites,json=historyPrewrites,proto3" json:"history_prewrites,omitempty"`
	NamespaceId              string                 `protobuf:"bytes,13,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	WorkflowId               string                 `protobuf:"bytes,14,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId                    string                 `protobuf:"bytes,15,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	PageSize                 int64                  `protobuf:"varint,16,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NextPageToken            []byte                 `protobuf:"bytes,17,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ExecutionCommand) Reset() {
	*x = ExecutionCommand{}
	mi := &file_xenon_v1_execution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCommand) ProtoMessage() {}

func (x *ExecutionCommand) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCommand.ProtoReflect.Descriptor instead.
func (*ExecutionCommand) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{5}
}

func (x *ExecutionCommand) GetKind() ExecutionCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return ExecutionCommand_UNSPECIFIED
}

func (x *ExecutionCommand) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ExecutionCommand) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *ExecutionCommand) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *ExecutionCommand) GetArchetypeId() uint32 {
	if x != nil {
		return x.ArchetypeId
	}
	return 0
}

func (x *ExecutionCommand) GetPreviousRunId() string {
	if x != nil {
		return x.PreviousRunId
	}
	return ""
}

func (x *ExecutionCommand) GetPreviousLastWriteVersion() int64 {
	if x != nil {
		return x.PreviousLastWriteVersion
	}
	return 0
}

func (x *ExecutionCommand) GetSnapshot() *ExecutionImage {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ExecutionCommand) GetMutation() *ExecutionMutation {
	if x != nil {
		return x.Mutation
	}
	return nil
}

func (x *ExecutionCommand) GetNewSnapshot() *ExecutionImage {
	if x != nil {
		return x.NewSnapshot
	}
	return nil
}

func (x *ExecutionCommand) GetCurrentMutation() *ExecutionMutation {
	if x != nil {
		return x.CurrentMutation
	}
	return nil
}

func (x *ExecutionCommand) GetHistoryPrewrites() []*HistoryCommand {
	if x != nil {
		return x.HistoryPrewrites
	}
	return nil
}

func (x *ExecutionCommand) GetNamespaceId() string {
	if x != nil {
		return x.NamespaceId
	}
	return ""
}

func (x *ExecutionCommand) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *ExecutionCommand) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionCommand) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ExecutionCommand) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type ExecutionCurrent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RunId            string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	StateProto       []byte                 `protobuf:"bytes,2,opt,name=state_proto,json=stateProto,proto3" json:"state_proto,omitempty"`
	StateBlob        *HistoryBlob           `protobuf:"bytes,3,opt,name=state_blob,json=stateBlob,proto3" json:"state_blob,omitempty"`
	LastWriteVersion int64                  `protobuf:"varint,4,opt,name=last_write_version,json=lastWriteVersion,proto3" json:"last_write_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutionCurrent) Reset() {
	*x = ExecutionCurrent{}
	mi := &file_xenon_v1_execution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionCurrent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionCurrent) ProtoMessage() {}

func (x *ExecutionCurrent) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionCurrent.ProtoReflect.Descriptor instead.
func (*ExecutionCurrent) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{6}
}

func (x *ExecutionCurrent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ExecutionCurrent) GetStateProto() []byte {
	if x != nil {
		return x.StateProto
	}
	return nil
}

func (x *ExecutionCurrent) GetStateBlob() *HistoryBlob {
	if x != nil {
		return x.StateBlob
	}
	return nil
}

func (x *ExecutionCurrent) GetLastWriteVersion() int64 {
	if x != nil {
		return x.LastWriteVersion
	}
	return 0
}

type ExecutionResult struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Error                 ExecutionResult_Error  `protobuf:"varint,1,opt,name=error,proto3,enum=xenon.v1.ExecutionResult_Error" json:"error,omitempty"`
	Message               string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Image                 *ExecutionImage        `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Current               *ExecutionCurrent      `protobuf:"bytes,4,opt,name=current,proto3" json:"current,omitempty"`
	ActualNextEventId     int64                  `protobuf:"varint,5,opt,name=actual_next_event_id,json=actualNextEventId,proto3" json:"actual_next_event_id,omitempty"`
	ActualDbRecordVersion int64                  `protobuf:"varint,6,opt,name=actual_db_record_version,json=actualDbRecordVersion,proto3" json:"actual_db_record_version,omitempty"`
	ShardId               int32                  `protobuf:"varint,7,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	Images                []*ExecutionImage      `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	NextPageToken         []byte                 `protobuf:"bytes,9,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExecutionResult) Reset() {
	*x = ExecutionResult{}
	mi := &file_xenon_v1_execution_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionResult) ProtoMessage() {}

func (x *ExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_execution_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionResult.ProtoReflect.Descriptor instead.
func (*ExecutionResult) Descriptor() ([]byte, []int) {
	return file_xenon_v1_execution_proto_rawDescGZIP(), []int{7}
}

func (x *ExecutionResult) GetError() ExecutionResult_Error {
	if x != nil {
		return x.Error
	}
	return ExecutionResult_NONE
}

func (x *ExecutionResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ExecutionResult) GetImage() *ExecutionImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ExecutionResult) GetCurrent() *ExecutionCurrent {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *ExecutionResult) GetActualNextEventId() int64 {
	if x != nil {
		return x.ActualNextEventId
	}
	return 0
}

func (x *ExecutionResult) GetActualDbRecordVersion() int64 {
	if x != nil {
		return x.ActualDbRecordVersion
	}
	return 0
}

func (x *ExecutionResult) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *ExecutionResult) GetImages() []*ExecutionImage {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *ExecutionResult) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

var File_xenon_v1_execution_proto protoreflect.FileDescriptor

const file_xenon_v1_execution_proto_rawDesc = "" +
	"\n" +
	"\x18xenon/v1/execution.proto\x12\bxenon.v1\x1a\x16xenon/v1/history.proto\"\xdb\x01\n" +
	"\x10ExecutionRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12%\n" +
	"\x0ecommand_sha256\x18\x04 \x01(\fR\rcommandSha256\x124\n" +
	"\acommand\x18\x05 \x01(\v2\x1a.xenon.v1.ExecutionCommandR\acommand\"\xb0\x01\n" +
	"\x12ExecutionChasmNode\x121\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.xenon.v1.HistoryBlobR\bmetadata\x12)\n" +
	"\x04data\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x04data\x12<\n" +
	"\x0ecassandra_blob\x18\x03 \x01(\v2\x15.xenon.v1.HistoryBlobR\rcassandraBlob\"\xdb\x01\n" +
	"\rExecutionTask\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x05R\n" +
	"categoryId\x12#\n" +
	"\rcategory_type\x18\x02 \x01(\x05R\fcategoryType\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\x03R\x06taskId\x12!\n" +
	"\ffire_seconds\x18\x04 \x01(\x03R\vfireSeconds\x12\x1d\n" +
	"\n" +
	"fire_nanos\x18\x05 \x01(\x05R\tfireNanos\x12)\n" +
	"\x04blob\x18\x06 \x01(\v2\x15.xenon.v1.HistoryBlobR\x04blob\"\xf9\f\n" +
	"\x0eExecutionImage\x12!\n" +
	"\fnamespace_id\x18\x01 \x01(\tR\vnamespaceId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x03 \x01(\tR\x05runId\x120\n" +
	"\x14execution_info_proto\x18\x04 \x01(\fR\x12executionInfoProto\x122\n" +
	"\x15execution_state_proto\x18\x05 \x01(\fR\x13executionStateProto\x12E\n" +
	"\x13execution_info_blob\x18\x06 \x01(\v2\x15.xenon.v1.HistoryBlobR\x11executionInfoBlob\x12G\n" +
	"\x14execution_state_blob\x18\a \x01(\v2\x15.xenon.v1.HistoryBlobR\x12executionStateBlob\x12\"\n" +
	"\rnext_event_id\x18\b \x01(\x03R\vnextEventId\x12#\n" +
	"\rstart_version\x18\t \x01(\x03R\fstartVersion\x12,\n" +
	"\x12last_write_version\x18\n" +
	" \x01(\x03R\x10lastWriteVersion\x12*\n" +
	"\x11db_record_version\x18\v \x01(\x03R\x0fdbRecordVersion\x12\x1c\n" +
	"\tcondition\x18\f \x01(\x03R\tcondition\x12H\n" +
	"\n" +
	"activities\x18\r \x03(\v2(.xenon.v1.ExecutionImage.ActivitiesEntryR\n" +
	"activities\x12<\n" +
	"\x06timers\x18\x0e \x03(\v2$.xenon.v1.ExecutionImage.TimersEntryR\x06timers\x12B\n" +
	"\bchildren\x18\x0f \x03(\v2&.xenon.v1.ExecutionImage.ChildrenEntryR\bchildren\x12?\n" +
	"\acancels\x18\x10 \x03(\v2%.xenon.v1.ExecutionImage.CancelsEntryR\acancels\x12?\n" +
	"\asignals\x18\x11 \x03(\v2%.xenon.v1.ExecutionImage.SignalsEntryR\asignals\x129\n" +
	"\x05chasm\x18\x12 \x03(\v2#.xenon.v1.ExecutionImage.ChasmEntryR\x05chasm\x120\n" +
	"\x14signal_requested_ids\x18\x13 \x03(\tR\x12signalRequestedIds\x12>\n" +
	"\x0fbuffered_events\x18\x14 \x03(\v2\x15.xenon.v1.HistoryBlobR\x0ebufferedEvents\x121\n" +
	"\bchecksum\x18\x15 \x01(\v2\x15.xenon.v1.HistoryBlobR\bchecksum\x12-\n" +
	"\x05tasks\x18\x16 \x03(\v2\x17.xenon.v1.ExecutionTaskR\x05tasks\x1aT\n" +
	"\x0fActivitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x05value:\x028\x01\x1aP\n" +
	"\vTimersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x05value:\x028\x01\x1aR\n" +
	"\rChildrenEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x05value:\x028\x01\x1aQ\n" +
	"\fCancelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x05value:\x028\x01\x1aQ\n" +
	"\fSignalsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.xenon.v1.HistoryBlobR\x05value:\x028\x01\x1aV\n" +
	"\n" +
	"ChasmEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.xenon.v1.ExecutionChasmNodeR\x05value:\x028\x01\"\xeb\x03\n" +
	"\x11ExecutionMutation\x120\n" +
	"\x06upsert\x18\x01 \x01(\v2\x18.xenon.v1.ExecutionImageR\x06upsert\x12+\n" +
	"\x11delete_activities\x18\x02 \x03(\x03R\x10deleteActivities\x12#\n" +
	"\rdelete_timers\x18\x03 \x03(\tR\fdeleteTimers\x12'\n" +
	"\x0fdelete_children\x18\x04 \x03(\x03R\x0edeleteChildren\x12%\n" +
	"\x0edelete_cancels\x18\x05 \x03(\x03R\rdeleteCancels\x12%\n" +
	"\x0edelete_signals\x18\x06 \x03(\x03R\rdeleteSignals\x12!\n" +
	"\fdelete_chasm\x18\a \x03(\tR\vdeleteChasm\x12=\n" +
	"\x1bdelete_signal_requested_ids\x18\b \x03(\tR\x18deleteSignalRequestedIds\x122\n" +
	"\x15clear_buffered_events\x18\t \x01(\bR\x13clearBufferedEvents\x12E\n" +
	"\x13new_buffered_events\x18\n" +
	" \x01(\v2\x15.xenon.v1.HistoryBlobR\x11newBufferedEvents\"\x8b\a\n" +
	"\x10ExecutionCommand\x123\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1f.xenon.v1.ExecutionCommand.KindR\x04kind\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x19\n" +
	"\brange_id\x18\x03 \x01(\x03R\arangeId\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\x05R\x04mode\x12!\n" +
	"\farchetype_id\x18\x05 \x01(\rR\varchetypeId\x12&\n" +
	"\x0fprevious_run_id\x18\x06 \x01(\tR\rpreviousRunId\x12=\n" +
	"\x1bprevious_last_write_version\x18\a \x01(\x03R\x18previousLastWriteVersion\x124\n" +
	"\bsnapshot\x18\b \x01(\v2\x18.xenon.v1.ExecutionImageR\bsnapshot\x127\n" +
	"\bmutation\x18\t \x01(\v2\x1b.xenon.v1.ExecutionMutationR\bmutation\x12;\n" +
	"\fnew_snapshot\x18\n" +
	" \x01(\v2\x18.xenon.v1.ExecutionImageR\vnewSnapshot\x12F\n" +
	"\x10current_mutation\x18\v \x01(\v2\x1b.xenon.v1.ExecutionMutationR\x0fcurrentMutation\x12E\n" +
	"\x11history_prewrites\x18\f \x03(\v2\x18.xenon.v1.HistoryCommandR\x10historyPrewrites\x12!\n" +
	"\fnamespace_id\x18\r \x01(\tR\vnamespaceId\x12\x1f\n" +
	"\vworkflow_id\x18\x0e \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x0f \x01(\tR\x05runId\x12\x1b\n" +
	"\tpage_size\x18\x10 \x01(\x03R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\x11 \x01(\fR\rnextPageToken\"\x92\x01\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06CREATE\x10\x01\x12\n" +
	"\n" +
	"\x06UPDATE\x10\x02\x12\x14\n" +
	"\x10CONFLICT_RESOLVE\x10\x03\x12\a\n" +
	"\x03SET\x10\x04\x12\a\n" +
	"\x03GET\x10\x05\x12\x0f\n" +
	"\vGET_CURRENT\x10\x06\x12\n" +
	"\n" +
	"\x06DELETE\x10\a\x12\x12\n" +
	"\x0eDELETE_CURRENT\x10\b\x12\b\n" +
	"\x04LIST\x10\t\"\xae\x01\n" +
	"\x10ExecutionCurrent\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1f\n" +
	"\vstate_proto\x18\x02 \x01(\fR\n" +
	"stateProto\x124\n" +
	"\n" +
	"state_blob\x18\x03 \x01(\v2\x15.xenon.v1.HistoryBlobR\tstateBlob\x12,\n" +
	"\x12last_write_version\x18\x04 \x01(\x03R\x10lastWriteVersion\"\xd0\x04\n" +
	"\x0fExecutionResult\x125\n" +
	"\x05error\x18\x01 \x01(\x0e2\x1f.xenon.v1.ExecutionResult.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12.\n" +
	"\x05image\x18\x03 \x01(\v2\x18.xenon.v1.ExecutionImageR\x05image\x124\n" +
	"\acurrent\x18\x04 \x01(\v2\x1a.xenon.v1.ExecutionCurrentR\acurrent\x12/\n" +
	"\x14actual_next_event_id\x18\x05 \x01(\x03R\x11actualNextEventId\x127\n" +
	"\x18actual_db_record_version\x18\x06 \x01(\x03R\x15actualDbRecordVersion\x12\x19\n" +
	"\bshard_id\x18\a \x01(\x05R\ashardId\x120\n" +
	"\x06images\x18\b \x03(\v2\x18.xenon.v1.ExecutionImageR\x06images\x12&\n" +
	"\x0fnext_page_token\x18\t \x01(\fR\rnextPageToken\"\xa6\x01\n" +
	"\x05Error\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x02\x12\f\n" +
	"\bINTERNAL\x10\x03\x12\x14\n" +
	"\x10CONDITION_FAILED\x10\x04\x12\x1d\n" +
	"\x19WORKFLOW_CONDITION_FAILED\x10\x05\x12\x1c\n" +
	"\x18CURRENT_CONDITION_FAILED\x10\x06\x12\x12\n" +
	"\x0eOWNERSHIP_LOST\x10\a2X\n" +
	"\x14ExecutionPersistence\x12@\n" +
	"\aExecute\x12\x1a.xenon.v1.ExecutionRequest\x1a\x19.xenon.v1.ExecutionResultB0Z.github.com/0x63616c/xenon/api/xenon/v1;xenonv1b\x06proto3"

var (
	file_xenon_v1_execution_proto_rawDescOnce sync.Once
	file_xenon_v1_execution_proto_rawDescData []byte
)

func file_xenon_v1_execution_proto_rawDescGZIP() []byte {
	file_xenon_v1_execution_proto_rawDescOnce.Do(func() {
		file_xenon_v1_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xenon_v1_execution_proto_rawDesc), len(file_xenon_v1_execution_proto_rawDesc)))
	})
	return file_xenon_v1_execution_proto_rawDescData
}

var file_xenon_v1_execution_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xenon_v1_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_xenon_v1_execution_proto_goTypes = []any{
	(ExecutionCommand_Kind)(0), // 0: xenon.v1.ExecutionCommand.Kind
	(ExecutionResult_Error)(0), // 1: xenon.v1.ExecutionResult.Error
	(*ExecutionRequest)(nil),   // 2: xenon.v1.ExecutionRequest
	(*ExecutionChasmNode)(nil), // 3: xenon.v1.ExecutionChasmNode
	(*ExecutionTask)(nil),      // 4: xenon.v1.ExecutionTask
	(*ExecutionImage)(nil),     // 5: xenon.v1.ExecutionImage
	(*ExecutionMutation)(nil),  // 6: xenon.v1.ExecutionMutation
	(*ExecutionCommand)(nil),   // 7: xenon.v1.ExecutionCommand
	(*ExecutionCurrent)(nil),   // 8: xenon.v1.ExecutionCurrent
	(*ExecutionResult)(nil),    // 9: xenon.v1.ExecutionResult
	nil,                        // 10: xenon.v1.ExecutionImage.ActivitiesEntry
	nil,                        // 11: xenon.v1.ExecutionImage.TimersEntry
	nil,                        // 12: xenon.v1.ExecutionImage.ChildrenEntry
	nil,                        // 13: xenon.v1.ExecutionImage.CancelsEntry
	nil,                        // 14: xenon.v1.ExecutionImage.SignalsEntry
	nil,                        // 15: xenon.v1.ExecutionImage.ChasmEntry
	(*HistoryBlob)(nil),        // 16: xenon.v1.HistoryBlob
	(*HistoryCommand)(nil),     // 17: xenon.v1.HistoryCommand
}
var file_xenon_v1_execution_proto_depIdxs = []int32{
	7,  // 0: xenon.v1.ExecutionRequest.command:type_name -> xenon.v1.ExecutionCommand
	16, // 1: xenon.v1.ExecutionChasmNode.metadata:type_name -> xenon.v1.HistoryBlob
	16, // 2: xenon.v1.ExecutionChasmNode.data:type_name -> xenon.v1.HistoryBlob
	16, // 3: xenon.v1.ExecutionChasmNode.cassandra_blob:type_name -> xenon.v1.HistoryBlob
	16, // 4: xenon.v1.ExecutionTask.blob:type_name -> xenon.v1.HistoryBlob
	16, // 5: xenon.v1.ExecutionImage.execution_info_blob:type_name -> xenon.v1.HistoryBlob
	16, // 6: xenon.v1.ExecutionImage.execution_state_blob:type_name -> xenon.v1.HistoryBlob
	10, // 7: xenon.v1.ExecutionImage.activities:type_name -> xenon.v1.ExecutionImage.ActivitiesEntry
	11, // 8: xenon.v1.ExecutionImage.timers:type_name -> xenon.v1.ExecutionImage.TimersEntry
	12, // 9: xenon.v1.ExecutionImage.children:type_name -> xenon.v1.ExecutionImage.ChildrenEntry
	13, // 10: xenon.v1.ExecutionImage.cancels:type_name -> xenon.v1.ExecutionImage.CancelsEntry
	14, // 11: xenon.v1.ExecutionImage.signals:type_name -> xenon.v1.ExecutionImage.SignalsEntry
	15, // 12: xenon.v1.ExecutionImage.chasm:type_name -> xenon.v1.ExecutionImage.ChasmEntry
	16, // 13: xenon.v1.ExecutionImage.buffered_events:type_name -> xenon.v1.HistoryBlob
	16, // 14: xenon.v1.ExecutionImage.checksum:type_name -> xenon.v1.HistoryBlob
	4,  // 15: xenon.v1.ExecutionImage.tasks:type_name -> xenon.v1.ExecutionTask
	5,  // 16: xenon.v1.ExecutionMutation.upsert:type_name -> xenon.v1.ExecutionImage
	16, // 17: xenon.v1.ExecutionMutation.new_buffered_events:type_name -> xenon.v1.HistoryBlob
	0,  // 18: xenon.v1.ExecutionCommand.kind:type_name -> xenon.v1.ExecutionCommand.Kind
	5,  // 19: xenon.v1.ExecutionCommand.snapshot:type_name -> xenon.v1.ExecutionImage
	6,  // 20: xenon.v1.ExecutionCommand.mutation:type_name -> xenon.v1.ExecutionMutation
	5,  // 21: xenon.v1.ExecutionCommand.new_snapshot:type_name -> xenon.v1.ExecutionImage
	6,  // 22: xenon.v1.ExecutionCommand.current_mutation:type_name -> xenon.v1.ExecutionMutation
	17, // 23: xenon.v1.ExecutionCommand.history_prewrites:type_name -> xenon.v1.HistoryCommand
	16, // 24: xenon.v1.ExecutionCurrent.state_blob:type_name -> xenon.v1.HistoryBlob
	1,  // 25: xenon.v1.ExecutionResult.error:type_name -> xenon.v1.ExecutionResult.Error
	5,  // 26: xenon.v1.ExecutionResult.image:type_name -> xenon.v1.ExecutionImage
	8,  // 27: xenon.v1.ExecutionResult.current:type_name -> xenon.v1.ExecutionCurrent
	5,  // 28: xenon.v1.ExecutionResult.images:type_name -> xenon.v1.ExecutionImage
	16, // 29: xenon.v1.ExecutionImage.ActivitiesEntry.value:type_name -> xenon.v1.HistoryBlob
	16, // 30: xenon.v1.ExecutionImage.TimersEntry.value:type_name -> xenon.v1.HistoryBlob
	16, // 31: xenon.v1.ExecutionImage.ChildrenEntry.value:type_name -> xenon.v1.HistoryBlob
	16, // 32: xenon.v1.ExecutionImage.CancelsEntry.value:type_name -> xenon.v1.HistoryBlob
	16, // 33: xenon.v1.ExecutionImage.SignalsEntry.value:type_name -> xenon.v1.HistoryBlob
	3,  // 34: xenon.v1.ExecutionImage.ChasmEntry.value:type_name -> xenon.v1.ExecutionChasmNode
	2,  // 35: xenon.v1.ExecutionPersistence.Execute:input_type -> xenon.v1.ExecutionRequest
	9,  // 36: xenon.v1.ExecutionPersistence.Execute:output_type -> xenon.v1.ExecutionResult
	36, // [36:37] is the sub-list for method output_type
	35, // [35:36] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_xenon_v1_execution_proto_init() }
func file_xenon_v1_execution_proto_init() {
	if File_xenon_v1_execution_proto != nil {
		return
	}
	file_xenon_v1_history_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xenon_v1_execution_proto_rawDesc), len(file_xenon_v1_execution_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xenon_v1_execution_proto_goTypes,
		DependencyIndexes: file_xenon_v1_execution_proto_depIdxs,
		EnumInfos:         file_xenon_v1_execution_proto_enumTypes,
		MessageInfos:      file_xenon_v1_execution_proto_msgTypes,
	}.Build()
	File_xenon_v1_execution_proto = out.File
	file_xenon_v1_execution_proto_goTypes = nil
	file_xenon_v1_execution_proto_depIdxs = nil
}
