// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: xenon/v1/history.proto

package xenonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HistoryCommand_Kind int32

const (
	HistoryCommand_UNSPECIFIED   HistoryCommand_Kind = 0
	HistoryCommand_APPEND        HistoryCommand_Kind = 1
	HistoryCommand_DELETE_NODE   HistoryCommand_Kind = 2
	HistoryCommand_READ          HistoryCommand_Kind = 3
	HistoryCommand_FORK          HistoryCommand_Kind = 4
	HistoryCommand_DELETE_BRANCH HistoryCommand_Kind = 5
	HistoryCommand_LIST_TREES    HistoryCommand_Kind = 6
	HistoryCommand_GET_TREE      HistoryCommand_Kind = 7
)

// Enum value maps for HistoryCommand_Kind.
var (
	HistoryCommand_Kind_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "APPEND",
		2: "DELETE_NODE",
		3: "READ",
		4: "FORK",
		5: "DELETE_BRANCH",
		6: "LIST_TREES",
		7: "GET_TREE",
	}
	HistoryCommand_Kind_value = map[string]int32{
		"UNSPECIFIED":   0,
		"APPEND":        1,
		"DELETE_NODE":   2,
		"READ":          3,
		"FORK":          4,
		"DELETE_BRANCH": 5,
		"LIST_TREES":    6,
		"GET_TREE":      7,
	}
)

func (x HistoryCommand_Kind) Enum() *HistoryCommand_Kind {
	p := new(HistoryCommand_Kind)
	*p = x
	return p
}

func (x HistoryCommand_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryCommand_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_history_proto_enumTypes[0].Descriptor()
}

func (HistoryCommand_Kind) Type() protoreflect.EnumType {
	return &file_xenon_v1_history_proto_enumTypes[0]
}

func (x HistoryCommand_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryCommand_Kind.Descriptor instead.
func (HistoryCommand_Kind) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{5, 0}
}

type HistoryResult_Error int32

const (
	HistoryResult_NONE             HistoryResult_Error = 0
	HistoryResult_UNAVAILABLE      HistoryResult_Error = 1
	HistoryResult_CONDITION_FAILED HistoryResult_Error = 2
	HistoryResult_INVALID_REQUEST  HistoryResult_Error = 3
	HistoryResult_APPEND_TIMEOUT   HistoryResult_Error = 4
	HistoryResult_INTERNAL         HistoryResult_Error = 5
)

// Enum value maps for HistoryResult_Error.
var (
	HistoryResult_Error_name = map[int32]string{
		0: "NONE",
		1: "UNAVAILABLE",
		2: "CONDITION_FAILED",
		3: "INVALID_REQUEST",
		4: "APPEND_TIMEOUT",
		5: "INTERNAL",
	}
	HistoryResult_Error_value = map[string]int32{
		"NONE":             0,
		"UNAVAILABLE":      1,
		"CONDITION_FAILED": 2,
		"INVALID_REQUEST":  3,
		"APPEND_TIMEOUT":   4,
		"INTERNAL":         5,
	}
)

func (x HistoryResult_Error) Enum() *HistoryResult_Error {
	p := new(HistoryResult_Error)
	*p = x
	return p
}

func (x HistoryResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HistoryResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_history_proto_enumTypes[1].Descriptor()
}

func (HistoryResult_Error) Type() protoreflect.EnumType {
	return &file_xenon_v1_history_proto_enumTypes[1]
}

func (x HistoryResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HistoryResult_Error.Descriptor instead.
func (HistoryResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{6, 0}
}

type HistoryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Partition       string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandSha256   []byte                 `protobuf:"bytes,4,opt,name=command_sha256,json=commandSha256,proto3" json:"command_sha256,omitempty"`
	Command         *HistoryCommand        `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_xenon_v1_history_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{0}
}

func (x *HistoryRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HistoryRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *HistoryRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *HistoryRequest) GetCommandSha256() []byte {
	if x != nil {
		return x.CommandSha256
	}
	return nil
}

func (x *HistoryRequest) GetCommand() *HistoryCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type HistoryBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryBlob) Reset() {
	*x = HistoryBlob{}
	mi := &file_xenon_v1_history_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryBlob) ProtoMessage() {}

func (x *HistoryBlob) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryBlob.ProtoReflect.Descriptor instead.
func (*HistoryBlob) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryBlob) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *HistoryBlob) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

type HistoryNodeRecord struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TransactionId         int64                  `protobuf:"varint,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	PreviousTransactionId int64                  `protobuf:"varint,3,opt,name=previous_transaction_id,json=previousTransactionId,proto3" json:"previous_transaction_id,omitempty"`
	Events                *HistoryBlob           `protobuf:"bytes,4,opt,name=events,proto3" json:"events,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *HistoryNodeRecord) Reset() {
	*x = HistoryNodeRecord{}
	mi := &file_xenon_v1_history_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryNodeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryNodeRecord) ProtoMessage() {}

func (x *HistoryNodeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryNodeRecord.ProtoReflect.Descriptor instead.
func (*HistoryNodeRecord) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{2}
}

func (x *HistoryNodeRecord) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *HistoryNodeRecord) GetTransactionId() int64 {
	if x != nil {
		return x.TransactionId
	}
	return 0
}

func (x *HistoryNodeRecord) GetPreviousTransactionId() int64 {
	if x != nil {
		return x.PreviousTransactionId
	}
	return 0
}

func (x *HistoryNodeRecord) GetEvents() *HistoryBlob {
	if x != nil {
		return x.Events
	}
	return nil
}

type HistoryTreeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShardId       int32                  `protobuf:"varint,1,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TreeId        []byte                 `protobuf:"bytes,2,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId      []byte                 `protobuf:"bytes,3,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Info          *HistoryBlob           `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryTreeRecord) Reset() {
	*x = HistoryTreeRecord{}
	mi := &file_xenon_v1_history_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryTreeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryTreeRecord) ProtoMessage() {}

func (x *HistoryTreeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryTreeRecord.ProtoReflect.Descriptor instead.
func (*HistoryTreeRecord) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryTreeRecord) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *HistoryTreeRecord) GetTreeId() []byte {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *HistoryTreeRecord) GetBranchId() []byte {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *HistoryTreeRecord) GetInfo() *HistoryBlob {
	if x != nil {
		return x.Info
	}
	return nil
}

type HistoryDeleteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BranchId      []byte                 `protobuf:"bytes,1,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	BeginNodeId   int64                  `protobuf:"varint,2,opt,name=begin_node_id,json=beginNodeId,proto3" json:"begin_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryDeleteRange) Reset() {
	*x = HistoryDeleteRange{}
	mi := &file_xenon_v1_history_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryDeleteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryDeleteRange) ProtoMessage() {}

func (x *HistoryDeleteRange) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryDeleteRange.ProtoReflect.Descriptor instead.
func (*HistoryDeleteRange) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryDeleteRange) GetBranchId() []byte {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *HistoryDeleteRange) GetBeginNodeId() int64 {
	if x != nil {
		return x.BeginNodeId
	}
	return 0
}

type HistoryCommand struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           HistoryCommand_Kind    `protobuf:"varint,1,opt,name=kind,proto3,enum=xenon.v1.HistoryCommand_Kind" json:"kind,omitempty"`
	ShardId        int32                  `protobuf:"varint,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	TreeId         []byte                 `protobuf:"bytes,3,opt,name=tree_id,json=treeId,proto3" json:"tree_id,omitempty"`
	BranchId       []byte                 `protobuf:"bytes,4,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	BranchInfo     []byte                 `protobuf:"bytes,5,opt,name=branch_info,json=branchInfo,proto3" json:"branch_info,omitempty"`
	BranchToken    []byte                 `protobuf:"bytes,6,opt,name=branch_token,json=branchToken,proto3" json:"branch_token,omitempty"`
	Node           *HistoryNodeRecord     `protobuf:"bytes,7,opt,name=node,proto3" json:"node,omitempty"`
	TreeInfo       *HistoryBlob           `protobuf:"bytes,8,opt,name=tree_info,json=treeInfo,proto3" json:"tree_info,omitempty"`
	IsNewBranch    bool                   `protobuf:"varint,9,opt,name=is_new_branch,json=isNewBranch,proto3" json:"is_new_branch,omitempty"`
	Info           string                 `protobuf:"bytes,10,opt,name=info,proto3" json:"info,omitempty"`
	NewBranchToken []byte                 `protobuf:"bytes,11,opt,name=new_branch_token,json=newBranchToken,proto3" json:"new_branch_token,omitempty"`
	ForkNodeId     int64                  `protobuf:"varint,12,opt,name=fork_node_id,json=forkNodeId,proto3" json:"fork_node_id,omitempty"`
	Ranges         []*HistoryDeleteRange  `protobuf:"bytes,13,rep,name=ranges,proto3" json:"ranges,omitempty"`
	MinNodeId      int64                  `protobuf:"varint,14,opt,name=min_node_id,json=minNodeId,proto3" json:"min_node_id,omitempty"`
	MaxNodeId      int64                  `protobuf:"varint,15,opt,name=max_node_id,json=maxNodeId,proto3" json:"max_node_id,omitempty"`
	PageSize       int64                  `protobuf:"varint,16,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NextPageToken  []byte                 `protobuf:"bytes,17,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	MetadataOnly   bool                   `protobuf:"varint,18,opt,name=metadata_only,json=metadataOnly,proto3" json:"metadata_only,omitempty"`
	ReverseOrder   bool                   `protobuf:"varint,19,opt,name=reverse_order,json=reverseOrder,proto3" json:"reverse_order,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HistoryCommand) Reset() {
	*x = HistoryCommand{}
	mi := &file_xenon_v1_history_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryCommand) ProtoMessage() {}

func (x *HistoryCommand) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryCommand.ProtoReflect.Descriptor instead.
func (*HistoryCommand) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{5}
}

func (x *HistoryCommand) GetKind() HistoryCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return HistoryCommand_UNSPECIFIED
}

func (x *HistoryCommand) GetShardId() int32 {
	if x != nil {
		return x.ShardId
	}
	return 0
}

func (x *HistoryCommand) GetTreeId() []byte {
	if x != nil {
		return x.TreeId
	}
	return nil
}

func (x *HistoryCommand) GetBranchId() []byte {
	if x != nil {
		return x.BranchId
	}
	return nil
}

func (x *HistoryCommand) GetBranchInfo() []byte {
	if x != nil {
		return x.BranchInfo
	}
	return nil
}

func (x *HistoryCommand) GetBranchToken() []byte {
	if x != nil {
		return x.BranchToken
	}
	return nil
}

func (x *HistoryCommand) GetNode() *HistoryNodeRecord {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *HistoryCommand) GetTreeInfo() *HistoryBlob {
	if x != nil {
		return x.TreeInfo
	}
	return nil
}

func (x *HistoryCommand) GetIsNewBranch() bool {
	if x != nil {
		return x.IsNewBranch
	}
	return false
}

func (x *HistoryCommand) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *HistoryCommand) GetNewBranchToken() []byte {
	if x != nil {
		return x.NewBranchToken
	}
	return nil
}

func (x *HistoryCommand) GetForkNodeId() int64 {
	if x != nil {
		return x.ForkNodeId
	}
	return 0
}

func (x *HistoryCommand) GetRanges() []*HistoryDeleteRange {
	if x != nil {
		return x.Ranges
	}
	return nil
}

func (x *HistoryCommand) GetMinNodeId() int64 {
	if x != nil {
		return x.MinNodeId
	}
	return 0
}

func (x *HistoryCommand) GetMaxNodeId() int64 {
	if x != nil {
		return x.MaxNodeId
	}
	return 0
}

func (x *HistoryCommand) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *HistoryCommand) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

func (x *HistoryCommand) GetMetadataOnly() bool {
	if x != nil {
		return x.MetadataOnly
	}
	return false
}

func (x *HistoryCommand) GetReverseOrder() bool {
	if x != nil {
		return x.ReverseOrder
	}
	return false
}

type HistoryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         HistoryResult_Error    `protobuf:"varint,1,opt,name=error,proto3,enum=xenon.v1.HistoryResult_Error" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Nodes         []*HistoryNodeRecord   `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Trees         []*HistoryTreeRecord   `protobuf:"bytes,4,rep,name=trees,proto3" json:"trees,omitempty"`
	NextPageToken []byte                 `protobuf:"bytes,5,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResult) Reset() {
	*x = HistoryResult{}
	mi := &file_xenon_v1_history_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResult) ProtoMessage() {}

func (x *HistoryResult) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_history_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResult.ProtoReflect.Descriptor instead.
func (*HistoryResult) Descriptor() ([]byte, []int) {
	return file_xenon_v1_history_proto_rawDescGZIP(), []int{6}
}

func (x *HistoryResult) GetError() HistoryResult_Error {
	if x != nil {
		return x.Error
	}
	return HistoryResult_NONE
}

func (x *HistoryResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HistoryResult) GetNodes() []*HistoryNodeRecord {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *HistoryResult) GetTrees() []*HistoryTreeRecord {
	if x != nil {
		return x.Trees
	}
	return nil
}

func (x *HistoryResult) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

var File_xenon_v1_history_proto protoreflect.FileDescriptor

const file_xenon_v1_history_proto_rawDesc = "" +
	"\n" +
	"\x16xenon/v1/history.proto\x12\bxenon.v1\"\xd7\x01\n" +
	"\x0eHistoryRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12%\n" +
	"\x0ecommand_sha256\x18\x04 \x01(\fR\rcommandSha256\x122\n" +
	"\acommand\x18\x05 \x01(\v2\x18.xenon.v1.HistoryCommandR\acommand\"=\n" +
	"\vHistoryBlob\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\x05R\bencoding\"\xba\x01\n" +
	"\x11HistoryNodeRecord\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\x03R\rtransactionId\x126\n" +
	"\x17previous_transaction_id\x18\x03 \x01(\x03R\x15previousTransactionId\x12-\n" +
	"\x06events\x18\x04 \x01(\v2\x15.xenon.v1.HistoryBlobR\x06events\"\x8f\x01\n" +
	"\x11HistoryTreeRecord\x12\x19\n" +
	"\bshard_id\x18\x01 \x01(\x05R\ashardId\x12\x17\n" +
	"\atree_id\x18\x02 \x01(\fR\x06treeId\x12\x1b\n" +
	"\tbranch_id\x18\x03 \x01(\fR\bbranchId\x12)\n" +
	"\x04info\x18\x04 \x01(\v2\x15.xenon.v1.HistoryBlobR\x04info\"U\n" +
	"\x12HistoryDeleteRange\x12\x1b\n" +
	"\tbranch_id\x18\x01 \x01(\fR\bbranchId\x12\"\n" +
	"\rbegin_node_id\x18\x02 \x01(\x03R\vbeginNodeId\"\xc1\x06\n" +
	"\x0eHistoryCommand\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.xenon.v1.HistoryCommand.KindR\x04kind\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\x05R\ashardId\x12\x17\n" +
	"\atree_id\x18\x03 \x01(\fR\x06treeId\x12\x1b\n" +
	"\tbranch_id\x18\x04 \x01(\fR\bbranchId\x12\x1f\n" +
	"\vbranch_info\x18\x05 \x01(\fR\n" +
	"branchInfo\x12!\n" +
	"\fbranch_token\x18\x06 \x01(\fR\vbranchToken\x12/\n" +
	"\x04node\x18\a \x01(\v2\x1b.xenon.v1.HistoryNodeRecordR\x04node\x122\n" +
	"\ttree_info\x18\b \x01(\v2\x15.xenon.v1.HistoryBlobR\btreeInfo\x12\"\n" +
	"\ris_new_branch\x18\t \x01(\bR\visNewBranch\x12\x12\n" +
	"\x04info\x18\n" +
	" \x01(\tR\x04info\x12(\n" +
	"\x10new_branch_token\x18\v \x01(\fR\x0enewBranchToken\x12 \n" +
	"\ffork_node_id\x18\f \x01(\x03R\n" +
	"forkNodeId\x124\n" +
	"\x06ranges\x18\r \x03(\v2\x1c.xenon.v1.HistoryDeleteRangeR\x06ranges\x12\x1e\n" +
	"\vmin_node_id\x18\x0e \x01(\x03R\tminNodeId\x12\x1e\n" +
	"\vmax_node_id\x18\x0f \x01(\x03R\tmaxNodeId\x12\x1b\n" +
	"\tpage_size\x18\x10 \x01(\x03R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\x11 \x01(\fR\rnextPageToken\x12#\n" +
	"\rmetadata_only\x18\x12 \x01(\bR\fmetadataOnly\x12#\n" +
	"\rreverse_order\x18\x13 \x01(\bR\freverseOrder\"y\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06APPEND\x10\x01\x12\x0f\n" +
	"\vDELETE_NODE\x10\x02\x12\b\n" +
	"\x04READ\x10\x03\x12\b\n" +
	"\x04FORK\x10\x04\x12\x11\n" +
	"\rDELETE_BRANCH\x10\x05\x12\x0e\n" +
	"\n" +
	"LIST_TREES\x10\x06\x12\f\n" +
	"\bGET_TREE\x10\a\"\xdd\x02\n" +
	"\rHistoryResult\x123\n" +
	"\x05error\x18\x01 \x01(\x0e2\x1d.xenon.v1.HistoryResult.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x121\n" +
	"\x05nodes\x18\x03 \x03(\v2\x1b.xenon.v1.HistoryNodeRecordR\x05nodes\x121\n" +
	"\x05trees\x18\x04 \x03(\v2\x1b.xenon.v1.HistoryTreeRecordR\x05trees\x12&\n" +
	"\x0fnext_page_token\x18\x05 \x01(\fR\rnextPageToken\"o\n" +
	"\x05Error\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x01\x12\x14\n" +
	"\x10CONDITION_FAILED\x10\x02\x12\x13\n" +
	"\x0fINVALID_REQUEST\x10\x03\x12\x12\n" +
	"\x0eAPPEND_TIMEOUT\x10\x04\x12\f\n" +
	"\bINTERNAL\x10\x052R\n" +
	"\x12HistoryPersistence\x12<\n" +
	"\aExecute\x12\x18.xenon.v1.HistoryRequest\x1a\x17.xenon.v1.HistoryResultB0Z.github.com/0x63616c/xenon/api/xenon/v1;xenonv1b\x06proto3"

var (
	file_xenon_v1_history_proto_rawDescOnce sync.Once
	file_xenon_v1_history_proto_rawDescData []byte
)

func file_xenon_v1_history_proto_rawDescGZIP() []byte {
	file_xenon_v1_history_proto_rawDescOnce.Do(func() {
		file_xenon_v1_history_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xenon_v1_history_proto_rawDesc), len(file_xenon_v1_history_proto_rawDesc)))
	})
	return file_xenon_v1_history_proto_rawDescData
}

var file_xenon_v1_history_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xenon_v1_history_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xenon_v1_history_proto_goTypes = []any{
	(HistoryCommand_Kind)(0),   // 0: xenon.v1.HistoryCommand.Kind
	(HistoryResult_Error)(0),   // 1: xenon.v1.HistoryResult.Error
	(*HistoryRequest)(nil),     // 2: xenon.v1.HistoryRequest
	(*HistoryBlob)(nil),        // 3: xenon.v1.HistoryBlob
	(*HistoryNodeRecord)(nil),  // 4: xenon.v1.HistoryNodeRecord
	(*HistoryTreeRecord)(nil),  // 5: xenon.v1.HistoryTreeRecord
	(*HistoryDeleteRange)(nil), // 6: xenon.v1.HistoryDeleteRange
	(*HistoryCommand)(nil),     // 7: xenon.v1.HistoryCommand
	(*HistoryResult)(nil),      // 8: xenon.v1.HistoryResult
}
var file_xenon_v1_history_proto_depIdxs = []int32{
	7,  // 0: xenon.v1.HistoryRequest.command:type_name -> xenon.v1.HistoryCommand
	3,  // 1: xenon.v1.HistoryNodeRecord.events:type_name -> xenon.v1.HistoryBlob
	3,  // 2: xenon.v1.HistoryTreeRecord.info:type_name -> xenon.v1.HistoryBlob
	0,  // 3: xenon.v1.HistoryCommand.kind:type_name -> xenon.v1.HistoryCommand.Kind
	4,  // 4: xenon.v1.HistoryCommand.node:type_name -> xenon.v1.HistoryNodeRecord
	3,  // 5: xenon.v1.HistoryCommand.tree_info:type_name -> xenon.v1.HistoryBlob
	6,  // 6: xenon.v1.HistoryCommand.ranges:type_name -> xenon.v1.HistoryDeleteRange
	1,  // 7: xenon.v1.HistoryResult.error:type_name -> xenon.v1.HistoryResult.Error
	4,  // 8: xenon.v1.HistoryResult.nodes:type_name -> xenon.v1.HistoryNodeRecord
	5,  // 9: xenon.v1.HistoryResult.trees:type_name -> xenon.v1.HistoryTreeRecord
	2,  // 10: xenon.v1.HistoryPersistence.Execute:input_type -> xenon.v1.HistoryRequest
	8,  // 11: xenon.v1.HistoryPersistence.Execute:output_type -> xenon.v1.HistoryResult
	11, // [11:12] is the sub-list for method output_type
	10, // [10:11] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_xenon_v1_history_proto_init() }
func file_xenon_v1_history_proto_init() {
	if File_xenon_v1_history_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xenon_v1_history_proto_rawDesc), len(file_xenon_v1_history_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xenon_v1_history_proto_goTypes,
		DependencyIndexes: file_xenon_v1_history_proto_depIdxs,
		EnumInfos:         file_xenon_v1_history_proto_enumTypes,
		MessageInfos:      file_xenon_v1_history_proto_msgTypes,
	}.Build()
	File_xenon_v1_history_proto = out.File
	file_xenon_v1_history_proto_goTypes = nil
	file_xenon_v1_history_proto_depIdxs = nil
}
