// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: xenon/v1/historytasks.proto

package xenonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistoryTasksPersistence_Execute_FullMethodName = "/xenon.v1.HistoryTasksPersistence/Execute"
)

// HistoryTasksPersistenceClient is the client API for HistoryTasksPersistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HistoryTasksPersistenceClient interface {
	Execute(ctx context.Context, in *HistoryTasksRequest, opts ...grpc.CallOption) (*HistoryTasksResult, error)
}

type historyTasksPersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistoryTasksPersistenceClient(cc grpc.ClientConnInterface) HistoryTasksPersistenceClient {
	return &historyTasksPersistenceClient{cc}
}

func (c *historyTasksPersistenceClient) Execute(ctx context.Context, in *HistoryTasksRequest, opts ...grpc.CallOption) (*HistoryTasksResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HistoryTasksResult)
	err := c.cc.Invoke(ctx, HistoryTasksPersistence_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistoryTasksPersistenceServer is the server API for HistoryTasksPersistence service.
// All implementations must embed UnimplementedHistoryTasksPersistenceServer
// for forward compatibility.
type HistoryTasksPersistenceServer interface {
	Execute(context.Context, *HistoryTasksRequest) (*HistoryTasksResult, error)
	mustEmbedUnimplementedHistoryTasksPersistenceServer()
}

// UnimplementedHistoryTasksPersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistoryTasksPersistenceServer struct{}

func (UnimplementedHistoryTasksPersistenceServer) Execute(context.Context, *HistoryTasksRequest) (*HistoryTasksResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedHistoryTasksPersistenceServer) mustEmbedUnimplementedHistoryTasksPersistenceServer() {
}
func (UnimplementedHistoryTasksPersistenceServer) testEmbeddedByValue() {}

// UnsafeHistoryTasksPersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistoryTasksPersistenceServer will
// result in compilation errors.
type UnsafeHistoryTasksPersistenceServer interface {
	mustEmbedUnimplementedHistoryTasksPersistenceServer()
}

func RegisterHistoryTasksPersistenceServer(s grpc.ServiceRegistrar, srv HistoryTasksPersistenceServer) {
	// If the following call pancis, it indicates UnimplementedHistoryTasksPersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistoryTasksPersistence_ServiceDesc, srv)
}

func _HistoryTasksPersistence_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HistoryTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistoryTasksPersistenceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistoryTasksPersistence_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistoryTasksPersistenceServer).Execute(ctx, req.(*HistoryTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistoryTasksPersistence_ServiceDesc is the grpc.ServiceDesc for HistoryTasksPersistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistoryTasksPersistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xenon.v1.HistoryTasksPersistence",
	HandlerType: (*HistoryTasksPersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _HistoryTasksPersistence_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xenon/v1/historytasks.proto",
}
