// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: xenon/v1/matching.proto

package xenonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchingCommand_Kind int32

const (
	MatchingCommand_UNSPECIFIED      MatchingCommand_Kind = 0
	MatchingCommand_CREATE_QUEUE     MatchingCommand_Kind = 1
	MatchingCommand_GET_QUEUE        MatchingCommand_Kind = 2
	MatchingCommand_UPDATE_QUEUE     MatchingCommand_Kind = 3
	MatchingCommand_LIST_QUEUES      MatchingCommand_Kind = 4
	MatchingCommand_DELETE_QUEUE     MatchingCommand_Kind = 5
	MatchingCommand_CREATE_TASKS     MatchingCommand_Kind = 6
	MatchingCommand_GET_TASKS        MatchingCommand_Kind = 7
	MatchingCommand_COMPLETE_TASKS   MatchingCommand_Kind = 8
	MatchingCommand_GET_USER_DATA    MatchingCommand_Kind = 9
	MatchingCommand_UPDATE_USER_DATA MatchingCommand_Kind = 10
	MatchingCommand_LIST_USER_DATA   MatchingCommand_Kind = 11
	MatchingCommand_GET_BY_BUILD     MatchingCommand_Kind = 12
	MatchingCommand_COUNT_BY_BUILD   MatchingCommand_Kind = 13
)

// Enum value maps for MatchingCommand_Kind.
var (
	MatchingCommand_Kind_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "CREATE_QUEUE",
		2:  "GET_QUEUE",
		3:  "UPDATE_QUEUE",
		4:  "LIST_QUEUES",
		5:  "DELETE_QUEUE",
		6:  "CREATE_TASKS",
		7:  "GET_TASKS",
		8:  "COMPLETE_TASKS",
		9:  "GET_USER_DATA",
		10: "UPDATE_USER_DATA",
		11: "LIST_USER_DATA",
		12: "GET_BY_BUILD",
		13: "COUNT_BY_BUILD",
	}
	MatchingCommand_Kind_value = map[string]int32{
		"UNSPECIFIED":      0,
		"CREATE_QUEUE":     1,
		"GET_QUEUE":        2,
		"UPDATE_QUEUE":     3,
		"LIST_QUEUES":      4,
		"DELETE_QUEUE":     5,
		"CREATE_TASKS":     6,
		"GET_TASKS":        7,
		"COMPLETE_TASKS":   8,
		"GET_USER_DATA":    9,
		"UPDATE_USER_DATA": 10,
		"LIST_USER_DATA":   11,
		"GET_BY_BUILD":     12,
		"COUNT_BY_BUILD":   13,
	}
)

func (x MatchingCommand_Kind) Enum() *MatchingCommand_Kind {
	p := new(MatchingCommand_Kind)
	*p = x
	return p
}

func (x MatchingCommand_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchingCommand_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_matching_proto_enumTypes[0].Descriptor()
}

func (MatchingCommand_Kind) Type() protoreflect.EnumType {
	return &file_xenon_v1_matching_proto_enumTypes[0]
}

func (x MatchingCommand_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchingCommand_Kind.Descriptor instead.
func (MatchingCommand_Kind) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{2, 0}
}

type MatchingResult_Error int32

const (
	MatchingResult_NONE             MatchingResult_Error = 0
	MatchingResult_NOT_FOUND        MatchingResult_Error = 1
	MatchingResult_CONDITION_FAILED MatchingResult_Error = 2
	MatchingResult_UNAVAILABLE      MatchingResult_Error = 3
)

// Enum value maps for MatchingResult_Error.
var (
	MatchingResult_Error_name = map[int32]string{
		0: "NONE",
		1: "NOT_FOUND",
		2: "CONDITION_FAILED",
		3: "UNAVAILABLE",
	}
	MatchingResult_Error_value = map[string]int32{
		"NONE":             0,
		"NOT_FOUND":        1,
		"CONDITION_FAILED": 2,
		"UNAVAILABLE":      3,
	}
)

func (x MatchingResult_Error) Enum() *MatchingResult_Error {
	p := new(MatchingResult_Error)
	*p = x
	return p
}

func (x MatchingResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MatchingResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_matching_proto_enumTypes[1].Descriptor()
}

func (MatchingResult_Error) Type() protoreflect.EnumType {
	return &file_xenon_v1_matching_proto_enumTypes[1]
}

func (x MatchingResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MatchingResult_Error.Descriptor instead.
func (MatchingResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{4, 0}
}

type MatchingRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RangeId       int64                  `protobuf:"varint,1,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingRecord) Reset() {
	*x = MatchingRecord{}
	mi := &file_xenon_v1_matching_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingRecord) ProtoMessage() {}

func (x *MatchingRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingRecord.ProtoReflect.Descriptor instead.
func (*MatchingRecord) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{0}
}

func (x *MatchingRecord) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *MatchingRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchingRecord) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

type MatchingTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subqueue      int32                  `protobuf:"varint,2,opt,name=subqueue,proto3" json:"subqueue,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Pass          int64                  `protobuf:"varint,5,opt,name=pass,proto3" json:"pass,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingTask) Reset() {
	*x = MatchingTask{}
	mi := &file_xenon_v1_matching_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingTask) ProtoMessage() {}

func (x *MatchingTask) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingTask.ProtoReflect.Descriptor instead.
func (*MatchingTask) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{1}
}

func (x *MatchingTask) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MatchingTask) GetSubqueue() int32 {
	if x != nil {
		return x.Subqueue
	}
	return 0
}

func (x *MatchingTask) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchingTask) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *MatchingTask) GetPass() int64 {
	if x != nil {
		return x.Pass
	}
	return 0
}

type MatchingCommand struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Kind            MatchingCommand_Kind   `protobuf:"varint,1,opt,name=kind,proto3,enum=xenon.v1.MatchingCommand_Kind" json:"kind,omitempty"`
	NamespaceId     []byte                 `protobuf:"bytes,2,opt,name=namespace_id,json=namespaceId,proto3" json:"namespace_id,omitempty"`
	Queue           string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	TaskType        int32                  `protobuf:"varint,4,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	RangeId         int64                  `protobuf:"varint,5,opt,name=range_id,json=rangeId,proto3" json:"range_id,omitempty"`
	PreviousRangeId int64                  `protobuf:"varint,6,opt,name=previous_range_id,json=previousRangeId,proto3" json:"previous_range_id,omitempty"`
	Data            []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	Encoding        int32                  `protobuf:"varint,8,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Tasks           []*MatchingTask        `protobuf:"bytes,9,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Subqueue        int32                  `protobuf:"varint,10,opt,name=subqueue,proto3" json:"subqueue,omitempty"`
	MinId           int64                  `protobuf:"varint,11,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	MaxId           int64                  `protobuf:"varint,12,opt,name=max_id,json=maxId,proto3" json:"max_id,omitempty"`
	PageSize        int32                  `protobuf:"varint,13,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Token           []byte                 `protobuf:"bytes,14,opt,name=token,proto3" json:"token,omitempty"`
	Updates         []*MatchingUserUpdate  `protobuf:"bytes,15,rep,name=updates,proto3" json:"updates,omitempty"`
	BuildId         string                 `protobuf:"bytes,16,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	Fair            bool                   `protobuf:"varint,17,opt,name=fair,proto3" json:"fair,omitempty"`
	MinPass         int64                  `protobuf:"varint,18,opt,name=min_pass,json=minPass,proto3" json:"min_pass,omitempty"`
	MaxPass         int64                  `protobuf:"varint,19,opt,name=max_pass,json=maxPass,proto3" json:"max_pass,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchingCommand) Reset() {
	*x = MatchingCommand{}
	mi := &file_xenon_v1_matching_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingCommand) ProtoMessage() {}

func (x *MatchingCommand) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingCommand.ProtoReflect.Descriptor instead.
func (*MatchingCommand) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{2}
}

func (x *MatchingCommand) GetKind() MatchingCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return MatchingCommand_UNSPECIFIED
}

func (x *MatchingCommand) GetNamespaceId() []byte {
	if x != nil {
		return x.NamespaceId
	}
	return nil
}

func (x *MatchingCommand) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *MatchingCommand) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *MatchingCommand) GetRangeId() int64 {
	if x != nil {
		return x.RangeId
	}
	return 0
}

func (x *MatchingCommand) GetPreviousRangeId() int64 {
	if x != nil {
		return x.PreviousRangeId
	}
	return 0
}

func (x *MatchingCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchingCommand) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *MatchingCommand) GetTasks() []*MatchingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *MatchingCommand) GetSubqueue() int32 {
	if x != nil {
		return x.Subqueue
	}
	return 0
}

func (x *MatchingCommand) GetMinId() int64 {
	if x != nil {
		return x.MinId
	}
	return 0
}

func (x *MatchingCommand) GetMaxId() int64 {
	if x != nil {
		return x.MaxId
	}
	return 0
}

func (x *MatchingCommand) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *MatchingCommand) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *MatchingCommand) GetUpdates() []*MatchingUserUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

func (x *MatchingCommand) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *MatchingCommand) GetFair() bool {
	if x != nil {
		return x.Fair
	}
	return false
}

func (x *MatchingCommand) GetMinPass() int64 {
	if x != nil {
		return x.MinPass
	}
	return 0
}

func (x *MatchingCommand) GetMaxPass() int64 {
	if x != nil {
		return x.MaxPass
	}
	return 0
}

type MatchingRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Partition       string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandSha256   []byte                 `protobuf:"bytes,4,opt,name=command_sha256,json=commandSha256,proto3" json:"command_sha256,omitempty"`
	Command         *MatchingCommand       `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchingRequest) Reset() {
	*x = MatchingRequest{}
	mi := &file_xenon_v1_matching_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingRequest) ProtoMessage() {}

func (x *MatchingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingRequest.ProtoReflect.Descriptor instead.
func (*MatchingRequest) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{3}
}

func (x *MatchingRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *MatchingRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *MatchingRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *MatchingRequest) GetCommandSha256() []byte {
	if x != nil {
		return x.CommandSha256
	}
	return nil
}

func (x *MatchingRequest) GetCommand() *MatchingCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type MatchingResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         MatchingResult_Error   `protobuf:"varint,1,opt,name=error,proto3,enum=xenon.v1.MatchingResult_Error" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Queues        []*MatchingRecord      `protobuf:"bytes,3,rep,name=queues,proto3" json:"queues,omitempty"`
	Tasks         []*MatchingTask        `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	Token         []byte                 `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	Completed     int32                  `protobuf:"varint,6,opt,name=completed,proto3" json:"completed,omitempty"`
	UserData      []*MatchingUserRecord  `protobuf:"bytes,7,rep,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	QueueNames    []string               `protobuf:"bytes,8,rep,name=queue_names,json=queueNames,proto3" json:"queue_names,omitempty"`
	Conflicting   []string               `protobuf:"bytes,9,rep,name=conflicting,proto3" json:"conflicting,omitempty"`
	Applied       bool                   `protobuf:"varint,10,opt,name=applied,proto3" json:"applied,omitempty"`
	Count         int64                  `protobuf:"varint,11,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingResult) Reset() {
	*x = MatchingResult{}
	mi := &file_xenon_v1_matching_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingResult) ProtoMessage() {}

func (x *MatchingResult) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingResult.ProtoReflect.Descriptor instead.
func (*MatchingResult) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{4}
}

func (x *MatchingResult) GetError() MatchingResult_Error {
	if x != nil {
		return x.Error
	}
	return MatchingResult_NONE
}

func (x *MatchingResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MatchingResult) GetQueues() []*MatchingRecord {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *MatchingResult) GetTasks() []*MatchingTask {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *MatchingResult) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *MatchingResult) GetCompleted() int32 {
	if x != nil {
		return x.Completed
	}
	return 0
}

func (x *MatchingResult) GetUserData() []*MatchingUserRecord {
	if x != nil {
		return x.UserData
	}
	return nil
}

func (x *MatchingResult) GetQueueNames() []string {
	if x != nil {
		return x.QueueNames
	}
	return nil
}

func (x *MatchingResult) GetConflicting() []string {
	if x != nil {
		return x.Conflicting
	}
	return nil
}

func (x *MatchingResult) GetApplied() bool {
	if x != nil {
		return x.Applied
	}
	return false
}

func (x *MatchingResult) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type MatchingUserRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchingUserRecord) Reset() {
	*x = MatchingUserRecord{}
	mi := &file_xenon_v1_matching_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingUserRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingUserRecord) ProtoMessage() {}

func (x *MatchingUserRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingUserRecord.ProtoReflect.Descriptor instead.
func (*MatchingUserRecord) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{5}
}

func (x *MatchingUserRecord) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *MatchingUserRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MatchingUserRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchingUserRecord) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

type MatchingUserUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Queue           string                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	Version         int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Data            []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Encoding        int32                  `protobuf:"varint,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	BuildIdsAdded   []string               `protobuf:"bytes,5,rep,name=build_ids_added,json=buildIdsAdded,proto3" json:"build_ids_added,omitempty"`
	BuildIdsRemoved []string               `protobuf:"bytes,6,rep,name=build_ids_removed,json=buildIdsRemoved,proto3" json:"build_ids_removed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchingUserUpdate) Reset() {
	*x = MatchingUserUpdate{}
	mi := &file_xenon_v1_matching_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchingUserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchingUserUpdate) ProtoMessage() {}

func (x *MatchingUserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_matching_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchingUserUpdate.ProtoReflect.Descriptor instead.
func (*MatchingUserUpdate) Descriptor() ([]byte, []int) {
	return file_xenon_v1_matching_proto_rawDescGZIP(), []int{6}
}

func (x *MatchingUserUpdate) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *MatchingUserUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *MatchingUserUpdate) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MatchingUserUpdate) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *MatchingUserUpdate) GetBuildIdsAdded() []string {
	if x != nil {
		return x.BuildIdsAdded
	}
	return nil
}

func (x *MatchingUserUpdate) GetBuildIdsRemoved() []string {
	if x != nil {
		return x.BuildIdsRemoved
	}
	return nil
}

var File_xenon_v1_matching_proto protoreflect.FileDescriptor

const file_xenon_v1_matching_proto_rawDesc = "" +
	"\n" +
	"\x17xenon/v1/matching.proto\x12\bxenon.v1\"[\n" +
	"\x0eMatchingRecord\x12\x19\n" +
	"\brange_id\x18\x01 \x01(\x03R\arangeId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\x05R\bencoding\"~\n" +
	"\fMatchingTask\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bsubqueue\x18\x02 \x01(\x05R\bsubqueue\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\x05R\bencoding\x12\x12\n" +
	"\x04pass\x18\x05 \x01(\x03R\x04pass\"\xe2\x06\n" +
	"\x0fMatchingCommand\x122\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1e.xenon.v1.MatchingCommand.KindR\x04kind\x12!\n" +
	"\fnamespace_id\x18\x02 \x01(\fR\vnamespaceId\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x1b\n" +
	"\ttask_type\x18\x04 \x01(\x05R\btaskType\x12\x19\n" +
	"\brange_id\x18\x05 \x01(\x03R\arangeId\x12*\n" +
	"\x11previous_range_id\x18\x06 \x01(\x03R\x0fpreviousRangeId\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\b \x01(\x05R\bencoding\x12,\n" +
	"\x05tasks\x18\t \x03(\v2\x16.xenon.v1.MatchingTaskR\x05tasks\x12\x1a\n" +
	"\bsubqueue\x18\n" +
	" \x01(\x05R\bsubqueue\x12\x15\n" +
	"\x06min_id\x18\v \x01(\x03R\x05minId\x12\x15\n" +
	"\x06max_id\x18\f \x01(\x03R\x05maxId\x12\x1b\n" +
	"\tpage_size\x18\r \x01(\x05R\bpageSize\x12\x14\n" +
	"\x05token\x18\x0e \x01(\fR\x05token\x126\n" +
	"\aupdates\x18\x0f \x03(\v2\x1c.xenon.v1.MatchingUserUpdateR\aupdates\x12\x19\n" +
	"\bbuild_id\x18\x10 \x01(\tR\abuildId\x12\x12\n" +
	"\x04fair\x18\x11 \x01(\bR\x04fair\x12\x19\n" +
	"\bmin_pass\x18\x12 \x01(\x03R\aminPass\x12\x19\n" +
	"\bmax_pass\x18\x13 \x01(\x03R\amaxPass\"\x85\x02\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCREATE_QUEUE\x10\x01\x12\r\n" +
	"\tGET_QUEUE\x10\x02\x12\x10\n" +
	"\fUPDATE_QUEUE\x10\x03\x12\x0f\n" +
	"\vLIST_QUEUES\x10\x04\x12\x10\n" +
	"\fDELETE_QUEUE\x10\x05\x12\x10\n" +
	"\fCREATE_TASKS\x10\x06\x12\r\n" +
	"\tGET_TASKS\x10\a\x12\x12\n" +
	"\x0eCOMPLETE_TASKS\x10\b\x12\x11\n" +
	"\rGET_USER_DATA\x10\t\x12\x14\n" +
	"\x10UPDATE_USER_DATA\x10\n" +
	"\x12\x12\n" +
	"\x0eLIST_USER_DATA\x10\v\x12\x10\n" +
	"\fGET_BY_BUILD\x10\f\x12\x12\n" +
	"\x0eCOUNT_BY_BUILD\x10\r\"\xd9\x01\n" +
	"\x0fMatchingRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12%\n" +
	"\x0ecommand_sha256\x18\x04 \x01(\fR\rcommandSha256\x123\n" +
	"\acommand\x18\x05 \x01(\v2\x19.xenon.v1.MatchingCommandR\acommand\"\xeb\x03\n" +
	"\x0eMatchingResult\x124\n" +
	"\x05error\x18\x01 \x01(\x0e2\x1e.xenon.v1.MatchingResult.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x120\n" +
	"\x06queues\x18\x03 \x03(\v2\x18.xenon.v1.MatchingRecordR\x06queues\x12,\n" +
	"\x05tasks\x18\x04 \x03(\v2\x16.xenon.v1.MatchingTaskR\x05tasks\x12\x14\n" +
	"\x05token\x18\x05 \x01(\fR\x05token\x12\x1c\n" +
	"\tcompleted\x18\x06 \x01(\x05R\tcompleted\x129\n" +
	"\tuser_data\x18\a \x03(\v2\x1c.xenon.v1.MatchingUserRecordR\buserData\x12\x1f\n" +
	"\vqueue_names\x18\b \x03(\tR\n" +
	"queueNames\x12 \n" +
	"\vconflicting\x18\t \x03(\tR\vconflicting\x12\x18\n" +
	"\aapplied\x18\n" +
	" \x01(\bR\aapplied\x12\x14\n" +
	"\x05count\x18\v \x01(\x03R\x05count\"G\n" +
	"\x05Error\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x14\n" +
	"\x10CONDITION_FAILED\x10\x02\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x03\"t\n" +
	"\x12MatchingUserRecord\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\x05R\bencoding\"\xc8\x01\n" +
	"\x12MatchingUserUpdate\x12\x14\n" +
	"\x05queue\x18\x01 \x01(\tR\x05queue\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\x05R\bencoding\x12&\n" +
	"\x0fbuild_ids_added\x18\x05 \x03(\tR\rbuildIdsAdded\x12*\n" +
	"\x11build_ids_removed\x18\x06 \x03(\tR\x0fbuildIdsRemoved2U\n" +
	"\x13MatchingPersistence\x12>\n" +
	"\aExecute\x12\x19.xenon.v1.MatchingRequest\x1a\x18.xenon.v1.MatchingResultB0Z.github.com/0x63616c/xenon/api/xenon/v1;xenonv1b\x06proto3"

var (
	file_xenon_v1_matching_proto_rawDescOnce sync.Once
	file_xenon_v1_matching_proto_rawDescData []byte
)

func file_xenon_v1_matching_proto_rawDescGZIP() []byte {
	file_xenon_v1_matching_proto_rawDescOnce.Do(func() {
		file_xenon_v1_matching_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xenon_v1_matching_proto_rawDesc), len(file_xenon_v1_matching_proto_rawDesc)))
	})
	return file_xenon_v1_matching_proto_rawDescData
}

var file_xenon_v1_matching_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xenon_v1_matching_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_xenon_v1_matching_proto_goTypes = []any{
	(MatchingCommand_Kind)(0),  // 0: xenon.v1.MatchingCommand.Kind
	(MatchingResult_Error)(0),  // 1: xenon.v1.MatchingResult.Error
	(*MatchingRecord)(nil),     // 2: xenon.v1.MatchingRecord
	(*MatchingTask)(nil),       // 3: xenon.v1.MatchingTask
	(*MatchingCommand)(nil),    // 4: xenon.v1.MatchingCommand
	(*MatchingRequest)(nil),    // 5: xenon.v1.MatchingRequest
	(*MatchingResult)(nil),     // 6: xenon.v1.MatchingResult
	(*MatchingUserRecord)(nil), // 7: xenon.v1.MatchingUserRecord
	(*MatchingUserUpdate)(nil), // 8: xenon.v1.MatchingUserUpdate
}
var file_xenon_v1_matching_proto_depIdxs = []int32{
	0, // 0: xenon.v1.MatchingCommand.kind:type_name -> xenon.v1.MatchingCommand.Kind
	3, // 1: xenon.v1.MatchingCommand.tasks:type_name -> xenon.v1.MatchingTask
	8, // 2: xenon.v1.MatchingCommand.updates:type_name -> xenon.v1.MatchingUserUpdate
	4, // 3: xenon.v1.MatchingRequest.command:type_name -> xenon.v1.MatchingCommand
	1, // 4: xenon.v1.MatchingResult.error:type_name -> xenon.v1.MatchingResult.Error
	2, // 5: xenon.v1.MatchingResult.queues:type_name -> xenon.v1.MatchingRecord
	3, // 6: xenon.v1.MatchingResult.tasks:type_name -> xenon.v1.MatchingTask
	7, // 7: xenon.v1.MatchingResult.user_data:type_name -> xenon.v1.MatchingUserRecord
	5, // 8: xenon.v1.MatchingPersistence.Execute:input_type -> xenon.v1.MatchingRequest
	6, // 9: xenon.v1.MatchingPersistence.Execute:output_type -> xenon.v1.MatchingResult
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_xenon_v1_matching_proto_init() }
func file_xenon_v1_matching_proto_init() {
	if File_xenon_v1_matching_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xenon_v1_matching_proto_rawDesc), len(file_xenon_v1_matching_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xenon_v1_matching_proto_goTypes,
		DependencyIndexes: file_xenon_v1_matching_proto_depIdxs,
		EnumInfos:         file_xenon_v1_matching_proto_enumTypes,
		MessageInfos:      file_xenon_v1_matching_proto_msgTypes,
	}.Build()
	File_xenon_v1_matching_proto = out.File
	file_xenon_v1_matching_proto_goTypes = nil
	file_xenon_v1_matching_proto_depIdxs = nil
}
