// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: xenon/v1/metadata.proto

package xenonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetadataPersistence_Execute_FullMethodName = "/xenon.v1.MetadataPersistence/Execute"
)

// MetadataPersistenceClient is the client API for MetadataPersistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Global namespace catalog and its notification counter occupy one control partition.
type MetadataPersistenceClient interface {
	Execute(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResult, error)
}

type metadataPersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataPersistenceClient(cc grpc.ClientConnInterface) MetadataPersistenceClient {
	return &metadataPersistenceClient{cc}
}

func (c *metadataPersistenceClient) Execute(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResult)
	err := c.cc.Invoke(ctx, MetadataPersistence_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataPersistenceServer is the server API for MetadataPersistence service.
// All implementations must embed UnimplementedMetadataPersistenceServer
// for forward compatibility.
//
// Global namespace catalog and its notification counter occupy one control partition.
type MetadataPersistenceServer interface {
	Execute(context.Context, *MetadataRequest) (*MetadataResult, error)
	mustEmbedUnimplementedMetadataPersistenceServer()
}

// UnimplementedMetadataPersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetadataPersistenceServer struct{}

func (UnimplementedMetadataPersistenceServer) Execute(context.Context, *MetadataRequest) (*MetadataResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedMetadataPersistenceServer) mustEmbedUnimplementedMetadataPersistenceServer() {}
func (UnimplementedMetadataPersistenceServer) testEmbeddedByValue()                             {}

// UnsafeMetadataPersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetadataPersistenceServer will
// result in compilation errors.
type UnsafeMetadataPersistenceServer interface {
	mustEmbedUnimplementedMetadataPersistenceServer()
}

func RegisterMetadataPersistenceServer(s grpc.ServiceRegistrar, srv MetadataPersistenceServer) {
	// If the following call pancis, it indicates UnimplementedMetadataPersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetadataPersistence_ServiceDesc, srv)
}

func _MetadataPersistence_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataPersistenceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetadataPersistence_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataPersistenceServer).Execute(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetadataPersistence_ServiceDesc is the grpc.ServiceDesc for MetadataPersistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetadataPersistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xenon.v1.MetadataPersistence",
	HandlerType: (*MetadataPersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _MetadataPersistence_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xenon/v1/metadata.proto",
}
