// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: xenon/v1/nexus.proto

package xenonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NexusPersistence_Execute_FullMethodName = "/xenon.v1.NexusPersistence/Execute"
)

// NexusPersistenceClient is the client API for NexusPersistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NexusPersistenceClient interface {
	Execute(ctx context.Context, in *NexusRequest, opts ...grpc.CallOption) (*NexusResult, error)
}

type nexusPersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewNexusPersistenceClient(cc grpc.ClientConnInterface) NexusPersistenceClient {
	return &nexusPersistenceClient{cc}
}

func (c *nexusPersistenceClient) Execute(ctx context.Context, in *NexusRequest, opts ...grpc.CallOption) (*NexusResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NexusResult)
	err := c.cc.Invoke(ctx, NexusPersistence_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NexusPersistenceServer is the server API for NexusPersistence service.
// All implementations must embed UnimplementedNexusPersistenceServer
// for forward compatibility.
type NexusPersistenceServer interface {
	Execute(context.Context, *NexusRequest) (*NexusResult, error)
	mustEmbedUnimplementedNexusPersistenceServer()
}

// UnimplementedNexusPersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNexusPersistenceServer struct{}

func (UnimplementedNexusPersistenceServer) Execute(context.Context, *NexusRequest) (*NexusResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedNexusPersistenceServer) mustEmbedUnimplementedNexusPersistenceServer() {}
func (UnimplementedNexusPersistenceServer) testEmbeddedByValue()                          {}

// UnsafeNexusPersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NexusPersistenceServer will
// result in compilation errors.
type UnsafeNexusPersistenceServer interface {
	mustEmbedUnimplementedNexusPersistenceServer()
}

func RegisterNexusPersistenceServer(s grpc.ServiceRegistrar, srv NexusPersistenceServer) {
	// If the following call pancis, it indicates UnimplementedNexusPersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NexusPersistence_ServiceDesc, srv)
}

func _NexusPersistence_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NexusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NexusPersistenceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NexusPersistence_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NexusPersistenceServer).Execute(ctx, req.(*NexusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NexusPersistence_ServiceDesc is the grpc.ServiceDesc for NexusPersistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NexusPersistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xenon.v1.NexusPersistence",
	HandlerType: (*NexusPersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _NexusPersistence_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xenon/v1/nexus.proto",
}
