// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: xenon/v1/queue.proto

package xenonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueuePersistence_Execute_FullMethodName = "/xenon.v1.QueuePersistence/Execute"
)

// QueuePersistenceClient is the client API for QueuePersistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueuePersistenceClient interface {
	Execute(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResult, error)
}

type queuePersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueuePersistenceClient(cc grpc.ClientConnInterface) QueuePersistenceClient {
	return &queuePersistenceClient{cc}
}

func (c *queuePersistenceClient) Execute(ctx context.Context, in *QueueRequest, opts ...grpc.CallOption) (*QueueResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueResult)
	err := c.cc.Invoke(ctx, QueuePersistence_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueuePersistenceServer is the server API for QueuePersistence service.
// All implementations must embed UnimplementedQueuePersistenceServer
// for forward compatibility.
type QueuePersistenceServer interface {
	Execute(context.Context, *QueueRequest) (*QueueResult, error)
	mustEmbedUnimplementedQueuePersistenceServer()
}

// UnimplementedQueuePersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueuePersistenceServer struct{}

func (UnimplementedQueuePersistenceServer) Execute(context.Context, *QueueRequest) (*QueueResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedQueuePersistenceServer) mustEmbedUnimplementedQueuePersistenceServer() {}
func (UnimplementedQueuePersistenceServer) testEmbeddedByValue()                          {}

// UnsafeQueuePersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueuePersistenceServer will
// result in compilation errors.
type UnsafeQueuePersistenceServer interface {
	mustEmbedUnimplementedQueuePersistenceServer()
}

func RegisterQueuePersistenceServer(s grpc.ServiceRegistrar, srv QueuePersistenceServer) {
	// If the following call pancis, it indicates UnimplementedQueuePersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueuePersistence_ServiceDesc, srv)
}

func _QueuePersistence_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuePersistenceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueuePersistence_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuePersistenceServer).Execute(ctx, req.(*QueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QueuePersistence_ServiceDesc is the grpc.ServiceDesc for QueuePersistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueuePersistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xenon.v1.QueuePersistence",
	HandlerType: (*QueuePersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _QueuePersistence_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xenon/v1/queue.proto",
}
