// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: xenon/v1/queuev2.proto

package xenonv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueV2Persistence_Execute_FullMethodName = "/xenon.v1.QueueV2Persistence/Execute"
)

// QueueV2PersistenceClient is the client API for QueueV2Persistence service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueV2PersistenceClient interface {
	Execute(ctx context.Context, in *QueueV2Request, opts ...grpc.CallOption) (*QueueV2Result, error)
}

type queueV2PersistenceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueV2PersistenceClient(cc grpc.ClientConnInterface) QueueV2PersistenceClient {
	return &queueV2PersistenceClient{cc}
}

func (c *queueV2PersistenceClient) Execute(ctx context.Context, in *QueueV2Request, opts ...grpc.CallOption) (*QueueV2Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueV2Result)
	err := c.cc.Invoke(ctx, QueueV2Persistence_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueV2PersistenceServer is the server API for QueueV2Persistence service.
// All implementations must embed UnimplementedQueueV2PersistenceServer
// for forward compatibility.
type QueueV2PersistenceServer interface {
	Execute(context.Context, *QueueV2Request) (*QueueV2Result, error)
	mustEmbedUnimplementedQueueV2PersistenceServer()
}

// UnimplementedQueueV2PersistenceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueV2PersistenceServer struct{}

func (UnimplementedQueueV2PersistenceServer) Execute(context.Context, *QueueV2Request) (*QueueV2Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedQueueV2PersistenceServer) mustEmbedUnimplementedQueueV2PersistenceServer() {}
func (UnimplementedQueueV2PersistenceServer) testEmbeddedByValue()                            {}

// UnsafeQueueV2PersistenceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueV2PersistenceServer will
// result in compilation errors.
type UnsafeQueueV2PersistenceServer interface {
	mustEmbedUnimplementedQueueV2PersistenceServer()
}

func RegisterQueueV2PersistenceServer(s grpc.ServiceRegistrar, srv QueueV2PersistenceServer) {
	// If the following call pancis, it indicates UnimplementedQueueV2PersistenceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueV2Persistence_ServiceDesc, srv)
}

func _QueueV2Persistence_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueueV2Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueV2PersistenceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueV2Persistence_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueV2PersistenceServer).Execute(ctx, req.(*QueueV2Request))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueV2Persistence_ServiceDesc is the grpc.ServiceDesc for QueueV2Persistence service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueV2Persistence_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xenon.v1.QueueV2Persistence",
	HandlerType: (*QueueV2PersistenceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _QueueV2Persistence_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "xenon/v1/queuev2.proto",
}
