// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: xenon/v1/queuev2.proto

package xenonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueV2Command_Kind int32

const (
	QueueV2Command_CREATE       QueueV2Command_Kind = 0
	QueueV2Command_ENQUEUE      QueueV2Command_Kind = 1
	QueueV2Command_READ         QueueV2Command_Kind = 2
	QueueV2Command_DELETE_RANGE QueueV2Command_Kind = 3
	QueueV2Command_LIST         QueueV2Command_Kind = 4
)

// Enum value maps for QueueV2Command_Kind.
var (
	QueueV2Command_Kind_name = map[int32]string{
		0: "CREATE",
		1: "ENQUEUE",
		2: "READ",
		3: "DELETE_RANGE",
		4: "LIST",
	}
	QueueV2Command_Kind_value = map[string]int32{
		"CREATE":       0,
		"ENQUEUE":      1,
		"READ":         2,
		"DELETE_RANGE": 3,
		"LIST":         4,
	}
)

func (x QueueV2Command_Kind) Enum() *QueueV2Command_Kind {
	p := new(QueueV2Command_Kind)
	*p = x
	return p
}

func (x QueueV2Command_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueV2Command_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_queuev2_proto_enumTypes[0].Descriptor()
}

func (QueueV2Command_Kind) Type() protoreflect.EnumType {
	return &file_xenon_v1_queuev2_proto_enumTypes[0]
}

func (x QueueV2Command_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueV2Command_Kind.Descriptor instead.
func (QueueV2Command_Kind) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{1, 0}
}

type QueueV2Result_Error int32

const (
	QueueV2Result_NONE                  QueueV2Result_Error = 0
	QueueV2Result_NOT_FOUND             QueueV2Result_Error = 1
	QueueV2Result_ALREADY_EXISTS        QueueV2Result_Error = 2
	QueueV2Result_INVALID_READ_TOKEN    QueueV2Result_Error = 3
	QueueV2Result_INVALID_LIST_TOKEN    QueueV2Result_Error = 4
	QueueV2Result_NONPOSITIVE_READ_SIZE QueueV2Result_Error = 5
	QueueV2Result_NONPOSITIVE_LIST_SIZE QueueV2Result_Error = 6
	QueueV2Result_NEGATIVE_OFFSET       QueueV2Result_Error = 7
	QueueV2Result_INVALID_DELETE_ID     QueueV2Result_Error = 8
	QueueV2Result_UNKNOWN_ENCODING      QueueV2Result_Error = 9
	QueueV2Result_INVALID_ARGUMENT      QueueV2Result_Error = 10
)

// Enum value maps for QueueV2Result_Error.
var (
	QueueV2Result_Error_name = map[int32]string{
		0:  "NONE",
		1:  "NOT_FOUND",
		2:  "ALREADY_EXISTS",
		3:  "INVALID_READ_TOKEN",
		4:  "INVALID_LIST_TOKEN",
		5:  "NONPOSITIVE_READ_SIZE",
		6:  "NONPOSITIVE_LIST_SIZE",
		7:  "NEGATIVE_OFFSET",
		8:  "INVALID_DELETE_ID",
		9:  "UNKNOWN_ENCODING",
		10: "INVALID_ARGUMENT",
	}
	QueueV2Result_Error_value = map[string]int32{
		"NONE":                  0,
		"NOT_FOUND":             1,
		"ALREADY_EXISTS":        2,
		"INVALID_READ_TOKEN":    3,
		"INVALID_LIST_TOKEN":    4,
		"NONPOSITIVE_READ_SIZE": 5,
		"NONPOSITIVE_LIST_SIZE": 6,
		"NEGATIVE_OFFSET":       7,
		"INVALID_DELETE_ID":     8,
		"UNKNOWN_ENCODING":      9,
		"INVALID_ARGUMENT":      10,
	}
)

func (x QueueV2Result_Error) Enum() *QueueV2Result_Error {
	p := new(QueueV2Result_Error)
	*p = x
	return p
}

func (x QueueV2Result_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueV2Result_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_queuev2_proto_enumTypes[1].Descriptor()
}

func (QueueV2Result_Error) Type() protoreflect.EnumType {
	return &file_xenon_v1_queuev2_proto_enumTypes[1]
}

func (x QueueV2Result_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueV2Result_Error.Descriptor instead.
func (QueueV2Result_Error) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{5, 0}
}

type QueueV2Request struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Partition       string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandSha256   []byte                 `protobuf:"bytes,4,opt,name=command_sha256,json=commandSha256,proto3" json:"command_sha256,omitempty"`
	Command         *QueueV2Command        `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueueV2Request) Reset() {
	*x = QueueV2Request{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2Request) ProtoMessage() {}

func (x *QueueV2Request) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2Request.ProtoReflect.Descriptor instead.
func (*QueueV2Request) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{0}
}

func (x *QueueV2Request) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *QueueV2Request) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *QueueV2Request) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *QueueV2Request) GetCommandSha256() []byte {
	if x != nil {
		return x.CommandSha256
	}
	return nil
}

func (x *QueueV2Request) GetCommand() *QueueV2Command {
	if x != nil {
		return x.Command
	}
	return nil
}

type QueueV2Command struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kind           QueueV2Command_Kind    `protobuf:"varint,1,opt,name=kind,proto3,enum=xenon.v1.QueueV2Command_Kind" json:"kind,omitempty"`
	QueueType      int64                  `protobuf:"varint,2,opt,name=queue_type,json=queueType,proto3" json:"queue_type,omitempty"`
	QueueName      string                 `protobuf:"bytes,3,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	Data           []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Encoding       int32                  `protobuf:"varint,5,opt,name=encoding,proto3" json:"encoding,omitempty"`
	HasBlob        bool                   `protobuf:"varint,6,opt,name=has_blob,json=hasBlob,proto3" json:"has_blob,omitempty"`
	PageSize       int64                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NextPageToken  []byte                 `protobuf:"bytes,8,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	InclusiveMaxId int64                  `protobuf:"varint,9,opt,name=inclusive_max_id,json=inclusiveMaxId,proto3" json:"inclusive_max_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueueV2Command) Reset() {
	*x = QueueV2Command{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2Command) ProtoMessage() {}

func (x *QueueV2Command) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2Command.ProtoReflect.Descriptor instead.
func (*QueueV2Command) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{1}
}

func (x *QueueV2Command) GetKind() QueueV2Command_Kind {
	if x != nil {
		return x.Kind
	}
	return QueueV2Command_CREATE
}

func (x *QueueV2Command) GetQueueType() int64 {
	if x != nil {
		return x.QueueType
	}
	return 0
}

func (x *QueueV2Command) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *QueueV2Command) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueueV2Command) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *QueueV2Command) GetHasBlob() bool {
	if x != nil {
		return x.HasBlob
	}
	return false
}

func (x *QueueV2Command) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueueV2Command) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

func (x *QueueV2Command) GetInclusiveMaxId() int64 {
	if x != nil {
		return x.InclusiveMaxId
	}
	return 0
}

type QueueV2Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,3,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueV2Entry) Reset() {
	*x = QueueV2Entry{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2Entry) ProtoMessage() {}

func (x *QueueV2Entry) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2Entry.ProtoReflect.Descriptor instead.
func (*QueueV2Entry) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{2}
}

func (x *QueueV2Entry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueueV2Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueueV2Entry) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

type QueueV2Info struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int64                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	LastId        int64                  `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueV2Info) Reset() {
	*x = QueueV2Info{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2Info) ProtoMessage() {}

func (x *QueueV2Info) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2Info.ProtoReflect.Descriptor instead.
func (*QueueV2Info) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{3}
}

func (x *QueueV2Info) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueV2Info) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *QueueV2Info) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

type QueueV2State struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MinId         int64                  `protobuf:"varint,2,opt,name=min_id,json=minId,proto3" json:"min_id,omitempty"`
	LastId        int64                  `protobuf:"varint,3,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueV2State) Reset() {
	*x = QueueV2State{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2State) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2State) ProtoMessage() {}

func (x *QueueV2State) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2State.ProtoReflect.Descriptor instead.
func (*QueueV2State) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{4}
}

func (x *QueueV2State) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueV2State) GetMinId() int64 {
	if x != nil {
		return x.MinId
	}
	return 0
}

func (x *QueueV2State) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

type QueueV2Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         QueueV2Result_Error    `protobuf:"varint,1,opt,name=error,proto3,enum=xenon.v1.QueueV2Result_Error" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Deleted       int64                  `protobuf:"varint,4,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Messages      []*QueueV2Entry        `protobuf:"bytes,5,rep,name=messages,proto3" json:"messages,omitempty"`
	Queues        []*QueueV2Info         `protobuf:"bytes,6,rep,name=queues,proto3" json:"queues,omitempty"`
	NextPageToken []byte                 `protobuf:"bytes,7,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueV2Result) Reset() {
	*x = QueueV2Result{}
	mi := &file_xenon_v1_queuev2_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueV2Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueV2Result) ProtoMessage() {}

func (x *QueueV2Result) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queuev2_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueV2Result.ProtoReflect.Descriptor instead.
func (*QueueV2Result) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queuev2_proto_rawDescGZIP(), []int{5}
}

func (x *QueueV2Result) GetError() QueueV2Result_Error {
	if x != nil {
		return x.Error
	}
	return QueueV2Result_NONE
}

func (x *QueueV2Result) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueueV2Result) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *QueueV2Result) GetDeleted() int64 {
	if x != nil {
		return x.Deleted
	}
	return 0
}

func (x *QueueV2Result) GetMessages() []*QueueV2Entry {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QueueV2Result) GetQueues() []*QueueV2Info {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *QueueV2Result) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

var File_xenon_v1_queuev2_proto protoreflect.FileDescriptor

const file_xenon_v1_queuev2_proto_rawDesc = "" +
	"\n" +
	"\x16xenon/v1/queuev2.proto\x12\bxenon.v1\"\xd7\x01\n" +
	"\x0eQueueV2Request\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12%\n" +
	"\x0ecommand_sha256\x18\x04 \x01(\fR\rcommandSha256\x122\n" +
	"\acommand\x18\x05 \x01(\v2\x18.xenon.v1.QueueV2CommandR\acommand\"\x82\x03\n" +
	"\x0eQueueV2Command\x121\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1d.xenon.v1.QueueV2Command.KindR\x04kind\x12\x1d\n" +
	"\n" +
	"queue_type\x18\x02 \x01(\x03R\tqueueType\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x03 \x01(\tR\tqueueName\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x05 \x01(\x05R\bencoding\x12\x19\n" +
	"\bhas_blob\x18\x06 \x01(\bR\ahasBlob\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x03R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\b \x01(\fR\rnextPageToken\x12(\n" +
	"\x10inclusive_max_id\x18\t \x01(\x03R\x0einclusiveMaxId\"E\n" +
	"\x04Kind\x12\n" +
	"\n" +
	"\x06CREATE\x10\x00\x12\v\n" +
	"\aENQUEUE\x10\x01\x12\b\n" +
	"\x04READ\x10\x02\x12\x10\n" +
	"\fDELETE_RANGE\x10\x03\x12\b\n" +
	"\x04LIST\x10\x04\"N\n" +
	"\fQueueV2Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x03 \x01(\x05R\bencoding\"P\n" +
	"\vQueueV2Info\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x03R\x05count\x12\x17\n" +
	"\alast_id\x18\x03 \x01(\x03R\x06lastId\"R\n" +
	"\fQueueV2State\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x15\n" +
	"\x06min_id\x18\x02 \x01(\x03R\x05minId\x12\x17\n" +
	"\alast_id\x18\x03 \x01(\x03R\x06lastId\"\x97\x04\n" +
	"\rQueueV2Result\x123\n" +
	"\x05error\x18\x01 \x01(\x0e2\x1d.xenon.v1.QueueV2Result.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\x03R\adeleted\x122\n" +
	"\bmessages\x18\x05 \x03(\v2\x16.xenon.v1.QueueV2EntryR\bmessages\x12-\n" +
	"\x06queues\x18\x06 \x03(\v2\x15.xenon.v1.QueueV2InfoR\x06queues\x12&\n" +
	"\x0fnext_page_token\x18\a \x01(\fR\rnextPageToken\"\xf2\x01\n" +
	"\x05Error\x12\b\n" +
	"\x04NONE\x10\x00\x12\r\n" +
	"\tNOT_FOUND\x10\x01\x12\x12\n" +
	"\x0eALREADY_EXISTS\x10\x02\x12\x16\n" +
	"\x12INVALID_READ_TOKEN\x10\x03\x12\x16\n" +
	"\x12INVALID_LIST_TOKEN\x10\x04\x12\x19\n" +
	"\x15NONPOSITIVE_READ_SIZE\x10\x05\x12\x19\n" +
	"\x15NONPOSITIVE_LIST_SIZE\x10\x06\x12\x13\n" +
	"\x0fNEGATIVE_OFFSET\x10\a\x12\x15\n" +
	"\x11INVALID_DELETE_ID\x10\b\x12\x14\n" +
	"\x10UNKNOWN_ENCODING\x10\t\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\n" +
	"2R\n" +
	"\x12QueueV2Persistence\x12<\n" +
	"\aExecute\x12\x18.xenon.v1.QueueV2Request\x1a\x17.xenon.v1.QueueV2ResultB0Z.github.com/0x63616c/xenon/api/xenon/v1;xenonv1b\x06proto3"

var (
	file_xenon_v1_queuev2_proto_rawDescOnce sync.Once
	file_xenon_v1_queuev2_proto_rawDescData []byte
)

func file_xenon_v1_queuev2_proto_rawDescGZIP() []byte {
	file_xenon_v1_queuev2_proto_rawDescOnce.Do(func() {
		file_xenon_v1_queuev2_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xenon_v1_queuev2_proto_rawDesc), len(file_xenon_v1_queuev2_proto_rawDesc)))
	})
	return file_xenon_v1_queuev2_proto_rawDescData
}

var file_xenon_v1_queuev2_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xenon_v1_queuev2_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_xenon_v1_queuev2_proto_goTypes = []any{
	(QueueV2Command_Kind)(0), // 0: xenon.v1.QueueV2Command.Kind
	(QueueV2Result_Error)(0), // 1: xenon.v1.QueueV2Result.Error
	(*QueueV2Request)(nil),   // 2: xenon.v1.QueueV2Request
	(*QueueV2Command)(nil),   // 3: xenon.v1.QueueV2Command
	(*QueueV2Entry)(nil),     // 4: xenon.v1.QueueV2Entry
	(*QueueV2Info)(nil),      // 5: xenon.v1.QueueV2Info
	(*QueueV2State)(nil),     // 6: xenon.v1.QueueV2State
	(*QueueV2Result)(nil),    // 7: xenon.v1.QueueV2Result
}
var file_xenon_v1_queuev2_proto_depIdxs = []int32{
	3, // 0: xenon.v1.QueueV2Request.command:type_name -> xenon.v1.QueueV2Command
	0, // 1: xenon.v1.QueueV2Command.kind:type_name -> xenon.v1.QueueV2Command.Kind
	1, // 2: xenon.v1.QueueV2Result.error:type_name -> xenon.v1.QueueV2Result.Error
	4, // 3: xenon.v1.QueueV2Result.messages:type_name -> xenon.v1.QueueV2Entry
	5, // 4: xenon.v1.QueueV2Result.queues:type_name -> xenon.v1.QueueV2Info
	2, // 5: xenon.v1.QueueV2Persistence.Execute:input_type -> xenon.v1.QueueV2Request
	7, // 6: xenon.v1.QueueV2Persistence.Execute:output_type -> xenon.v1.QueueV2Result
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_xenon_v1_queuev2_proto_init() }
func file_xenon_v1_queuev2_proto_init() {
	if File_xenon_v1_queuev2_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xenon_v1_queuev2_proto_rawDesc), len(file_xenon_v1_queuev2_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xenon_v1_queuev2_proto_goTypes,
		DependencyIndexes: file_xenon_v1_queuev2_proto_depIdxs,
		EnumInfos:         file_xenon_v1_queuev2_proto_enumTypes,
		MessageInfos:      file_xenon_v1_queuev2_proto_msgTypes,
	}.Build()
	File_xenon_v1_queuev2_proto = out.File
	file_xenon_v1_queuev2_proto_goTypes = nil
	file_xenon_v1_queuev2_proto_depIdxs = nil
}
