// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v7.36.0
// source: xenon/v1/queue.proto

package xenonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueCommand_Kind int32

const (
	QueueCommand_UNSPECIFIED      QueueCommand_Kind = 0
	QueueCommand_INIT             QueueCommand_Kind = 1
	QueueCommand_ENQUEUE          QueueCommand_Kind = 2
	QueueCommand_READ             QueueCommand_Kind = 3
	QueueCommand_DELETE_BEFORE    QueueCommand_Kind = 4
	QueueCommand_UPDATE_ACK       QueueCommand_Kind = 5
	QueueCommand_GET_ACK          QueueCommand_Kind = 6
	QueueCommand_ENQUEUE_DLQ      QueueCommand_Kind = 7
	QueueCommand_READ_DLQ         QueueCommand_Kind = 8
	QueueCommand_DELETE_DLQ       QueueCommand_Kind = 9
	QueueCommand_RANGE_DELETE_DLQ QueueCommand_Kind = 10
	QueueCommand_UPDATE_DLQ_ACK   QueueCommand_Kind = 11
	QueueCommand_GET_DLQ_ACK      QueueCommand_Kind = 12
)

// Enum value maps for QueueCommand_Kind.
var (
	QueueCommand_Kind_name = map[int32]string{
		0:  "UNSPECIFIED",
		1:  "INIT",
		2:  "ENQUEUE",
		3:  "READ",
		4:  "DELETE_BEFORE",
		5:  "UPDATE_ACK",
		6:  "GET_ACK",
		7:  "ENQUEUE_DLQ",
		8:  "READ_DLQ",
		9:  "DELETE_DLQ",
		10: "RANGE_DELETE_DLQ",
		11: "UPDATE_DLQ_ACK",
		12: "GET_DLQ_ACK",
	}
	QueueCommand_Kind_value = map[string]int32{
		"UNSPECIFIED":      0,
		"INIT":             1,
		"ENQUEUE":          2,
		"READ":             3,
		"DELETE_BEFORE":    4,
		"UPDATE_ACK":       5,
		"GET_ACK":          6,
		"ENQUEUE_DLQ":      7,
		"READ_DLQ":         8,
		"DELETE_DLQ":       9,
		"RANGE_DELETE_DLQ": 10,
		"UPDATE_DLQ_ACK":   11,
		"GET_DLQ_ACK":      12,
	}
)

func (x QueueCommand_Kind) Enum() *QueueCommand_Kind {
	p := new(QueueCommand_Kind)
	*p = x
	return p
}

func (x QueueCommand_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueCommand_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_queue_proto_enumTypes[0].Descriptor()
}

func (QueueCommand_Kind) Type() protoreflect.EnumType {
	return &file_xenon_v1_queue_proto_enumTypes[0]
}

func (x QueueCommand_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueCommand_Kind.Descriptor instead.
func (QueueCommand_Kind) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{1, 0}
}

type QueueResult_Error int32

const (
	QueueResult_NONE        QueueResult_Error = 0
	QueueResult_UNAVAILABLE QueueResult_Error = 1
	QueueResult_INTERNAL    QueueResult_Error = 2
)

// Enum value maps for QueueResult_Error.
var (
	QueueResult_Error_name = map[int32]string{
		0: "NONE",
		1: "UNAVAILABLE",
		2: "INTERNAL",
	}
	QueueResult_Error_value = map[string]int32{
		"NONE":        0,
		"UNAVAILABLE": 1,
		"INTERNAL":    2,
	}
)

func (x QueueResult_Error) Enum() *QueueResult_Error {
	p := new(QueueResult_Error)
	*p = x
	return p
}

func (x QueueResult_Error) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueResult_Error) Descriptor() protoreflect.EnumDescriptor {
	return file_xenon_v1_queue_proto_enumTypes[1].Descriptor()
}

func (QueueResult_Error) Type() protoreflect.EnumType {
	return &file_xenon_v1_queue_proto_enumTypes[1]
}

func (x QueueResult_Error) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueResult_Error.Descriptor instead.
func (QueueResult_Error) EnumDescriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{4, 0}
}

type QueueRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion uint32                 `protobuf:"varint,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Partition       string                 `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	OperationId     string                 `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	CommandSha256   []byte                 `protobuf:"bytes,4,opt,name=command_sha256,json=commandSha256,proto3" json:"command_sha256,omitempty"`
	Command         *QueueCommand          `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *QueueRequest) Reset() {
	*x = QueueRequest{}
	mi := &file_xenon_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueRequest) ProtoMessage() {}

func (x *QueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueRequest.ProtoReflect.Descriptor instead.
func (*QueueRequest) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *QueueRequest) GetPartition() string {
	if x != nil {
		return x.Partition
	}
	return ""
}

func (x *QueueRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *QueueRequest) GetCommandSha256() []byte {
	if x != nil {
		return x.CommandSha256
	}
	return nil
}

func (x *QueueRequest) GetCommand() *QueueCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type QueueCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          QueueCommand_Kind      `protobuf:"varint,1,opt,name=kind,proto3,enum=xenon.v1.QueueCommand_Kind" json:"kind,omitempty"`
	QueueType     int32                  `protobuf:"varint,2,opt,name=queue_type,json=queueType,proto3" json:"queue_type,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Version       int64                  `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	FirstId       int64                  `protobuf:"varint,6,opt,name=first_id,json=firstId,proto3" json:"first_id,omitempty"`
	LastId        int64                  `protobuf:"varint,7,opt,name=last_id,json=lastId,proto3" json:"last_id,omitempty"`
	PageSize      int64                  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	NextPageToken []byte                 `protobuf:"bytes,9,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueCommand) Reset() {
	*x = QueueCommand{}
	mi := &file_xenon_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueCommand) ProtoMessage() {}

func (x *QueueCommand) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueCommand.ProtoReflect.Descriptor instead.
func (*QueueCommand) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *QueueCommand) GetKind() QueueCommand_Kind {
	if x != nil {
		return x.Kind
	}
	return QueueCommand_UNSPECIFIED
}

func (x *QueueCommand) GetQueueType() int32 {
	if x != nil {
		return x.QueueType
	}
	return 0
}

func (x *QueueCommand) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueueCommand) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *QueueCommand) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *QueueCommand) GetFirstId() int64 {
	if x != nil {
		return x.FirstId
	}
	return 0
}

func (x *QueueCommand) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *QueueCommand) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *QueueCommand) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

type QueueEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueType     int32                  `protobuf:"varint,1,opt,name=queue_type,json=queueType,proto3" json:"queue_type,omitempty"`
	Id            int64                  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      string                 `protobuf:"bytes,4,opt,name=encoding,proto3" json:"encoding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueEntry) Reset() {
	*x = QueueEntry{}
	mi := &file_xenon_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueEntry) ProtoMessage() {}

func (x *QueueEntry) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueEntry.ProtoReflect.Descriptor instead.
func (*QueueEntry) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *QueueEntry) GetQueueType() int32 {
	if x != nil {
		return x.QueueType
	}
	return 0
}

func (x *QueueEntry) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *QueueEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueueEntry) GetEncoding() string {
	if x != nil {
		return x.Encoding
	}
	return ""
}

type QueueMetadataRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Encoding      int32                  `protobuf:"varint,2,opt,name=encoding,proto3" json:"encoding,omitempty"`
	Version       int64                  `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueMetadataRecord) Reset() {
	*x = QueueMetadataRecord{}
	mi := &file_xenon_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueMetadataRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueMetadataRecord) ProtoMessage() {}

func (x *QueueMetadataRecord) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueMetadataRecord.ProtoReflect.Descriptor instead.
func (*QueueMetadataRecord) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *QueueMetadataRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *QueueMetadataRecord) GetEncoding() int32 {
	if x != nil {
		return x.Encoding
	}
	return 0
}

func (x *QueueMetadataRecord) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type QueueResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         QueueResult_Error      `protobuf:"varint,1,opt,name=error,proto3,enum=xenon.v1.QueueResult_Error" json:"error,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Messages      []*QueueEntry          `protobuf:"bytes,4,rep,name=messages,proto3" json:"messages,omitempty"`
	Metadata      *QueueMetadataRecord   `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	NextPageToken []byte                 `protobuf:"bytes,6,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueResult) Reset() {
	*x = QueueResult{}
	mi := &file_xenon_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueResult) ProtoMessage() {}

func (x *QueueResult) ProtoReflect() protoreflect.Message {
	mi := &file_xenon_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueResult.ProtoReflect.Descriptor instead.
func (*QueueResult) Descriptor() ([]byte, []int) {
	return file_xenon_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *QueueResult) GetError() QueueResult_Error {
	if x != nil {
		return x.Error
	}
	return QueueResult_NONE
}

func (x *QueueResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *QueueResult) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *QueueResult) GetMessages() []*QueueEntry {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *QueueResult) GetMetadata() *QueueMetadataRecord {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *QueueResult) GetNextPageToken() []byte {
	if x != nil {
		return x.NextPageToken
	}
	return nil
}

var File_xenon_v1_queue_proto protoreflect.FileDescriptor

const file_xenon_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x14xenon/v1/queue.proto\x12\bxenon.v1\"\xd3\x01\n" +
	"\fQueueRequest\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\rR\x0fprotocolVersion\x12\x1c\n" +
	"\tpartition\x18\x02 \x01(\tR\tpartition\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12%\n" +
	"\x0ecommand_sha256\x18\x04 \x01(\fR\rcommandSha256\x120\n" +
	"\acommand\x18\x05 \x01(\v2\x16.xenon.v1.QueueCommandR\acommand\"\xf6\x03\n" +
	"\fQueueCommand\x12/\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x1b.xenon.v1.QueueCommand.KindR\x04kind\x12\x1d\n" +
	"\n" +
	"queue_type\x18\x02 \x01(\x05R\tqueueType\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\x05R\bencoding\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x03R\aversion\x12\x19\n" +
	"\bfirst_id\x18\x06 \x01(\x03R\afirstId\x12\x17\n" +
	"\alast_id\x18\a \x01(\x03R\x06lastId\x12\x1b\n" +
	"\tpage_size\x18\b \x01(\x03R\bpageSize\x12&\n" +
	"\x0fnext_page_token\x18\t \x01(\fR\rnextPageToken\"\xd2\x01\n" +
	"\x04Kind\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\b\n" +
	"\x04INIT\x10\x01\x12\v\n" +
	"\aENQUEUE\x10\x02\x12\b\n" +
	"\x04READ\x10\x03\x12\x11\n" +
	"\rDELETE_BEFORE\x10\x04\x12\x0e\n" +
	"\n" +
	"UPDATE_ACK\x10\x05\x12\v\n" +
	"\aGET_ACK\x10\x06\x12\x0f\n" +
	"\vENQUEUE_DLQ\x10\a\x12\f\n" +
	"\bREAD_DLQ\x10\b\x12\x0e\n" +
	"\n" +
	"DELETE_DLQ\x10\t\x12\x14\n" +
	"\x10RANGE_DELETE_DLQ\x10\n" +
	"\x12\x12\n" +
	"\x0eUPDATE_DLQ_ACK\x10\v\x12\x0f\n" +
	"\vGET_DLQ_ACK\x10\f\"k\n" +
	"\n" +
	"QueueEntry\x12\x1d\n" +
	"\n" +
	"queue_type\x18\x01 \x01(\x05R\tqueueType\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\x03R\x02id\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x04 \x01(\tR\bencoding\"_\n" +
	"\x13QueueMetadataRecord\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bencoding\x18\x02 \x01(\x05R\bencoding\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x03R\aversion\"\xc0\x02\n" +
	"\vQueueResult\x121\n" +
	"\x05error\x18\x01 \x01(\x0e2\x1b.xenon.v1.QueueResult.ErrorR\x05error\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x120\n" +
	"\bmessages\x18\x04 \x03(\v2\x14.xenon.v1.QueueEntryR\bmessages\x129\n" +
	"\bmetadata\x18\x05 \x01(\v2\x1d.xenon.v1.QueueMetadataRecordR\bmetadata\x12&\n" +
	"\x0fnext_page_token\x18\x06 \x01(\fR\rnextPageToken\"0\n" +
	"\x05Error\x12\b\n" +
	"\x04NONE\x10\x00\x12\x0f\n" +
	"\vUNAVAILABLE\x10\x01\x12\f\n" +
	"\bINTERNAL\x10\x022L\n" +
	"\x10QueuePersistence\x128\n" +
	"\aExecute\x12\x16.xenon.v1.QueueRequest\x1a\x15.xenon.v1.QueueResultB0Z.github.com/0x63616c/xenon/api/xenon/v1;xenonv1b\x06proto3"

var (
	file_xenon_v1_queue_proto_rawDescOnce sync.Once
	file_xenon_v1_queue_proto_rawDescData []byte
)

func file_xenon_v1_queue_proto_rawDescGZIP() []byte {
	file_xenon_v1_queue_proto_rawDescOnce.Do(func() {
		file_xenon_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xenon_v1_queue_proto_rawDesc), len(file_xenon_v1_queue_proto_rawDesc)))
	})
	return file_xenon_v1_queue_proto_rawDescData
}

var file_xenon_v1_queue_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_xenon_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_xenon_v1_queue_proto_goTypes = []any{
	(QueueCommand_Kind)(0),      // 0: xenon.v1.QueueCommand.Kind
	(QueueResult_Error)(0),      // 1: xenon.v1.QueueResult.Error
	(*QueueRequest)(nil),        // 2: xenon.v1.QueueRequest
	(*QueueCommand)(nil),        // 3: xenon.v1.QueueCommand
	(*QueueEntry)(nil),          // 4: xenon.v1.QueueEntry
	(*QueueMetadataRecord)(nil), // 5: xenon.v1.QueueMetadataRecord
	(*QueueResult)(nil),         // 6: xenon.v1.QueueResult
}
var file_xenon_v1_queue_proto_depIdxs = []int32{
	3, // 0: xenon.v1.QueueRequest.command:type_name -> xenon.v1.QueueCommand
	0, // 1: xenon.v1.QueueCommand.kind:type_name -> xenon.v1.QueueCommand.Kind
	1, // 2: xenon.v1.QueueResult.error:type_name -> xenon.v1.QueueResult.Error
	4, // 3: xenon.v1.QueueResult.messages:type_name -> xenon.v1.QueueEntry
	5, // 4: xenon.v1.QueueResult.metadata:type_name -> xenon.v1.QueueMetadataRecord
	2, // 5: xenon.v1.QueuePersistence.Execute:input_type -> xenon.v1.QueueRequest
	6, // 6: xenon.v1.QueuePersistence.Execute:output_type -> xenon.v1.QueueResult
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_xenon_v1_queue_proto_init() }
func file_xenon_v1_queue_proto_init() {
	if File_xenon_v1_queue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xenon_v1_queue_proto_rawDesc), len(file_xenon_v1_queue_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xenon_v1_queue_proto_goTypes,
		DependencyIndexes: file_xenon_v1_queue_proto_depIdxs,
		EnumInfos:         file_xenon_v1_queue_proto_enumTypes,
		MessageInfos:      file_xenon_v1_queue_proto_msgTypes,
	}.Build()
	File_xenon_v1_queue_proto = out.File
	file_xenon_v1_queue_proto_goTypes = nil
	file_xenon_v1_queue_proto_depIdxs = nil
}
